// NBA Finals champion dataset.
// Each row's `year` is the year the Finals ended (1946-47 season = year 1947).
// 1947-1949 Finals were contested in the BAA; the BAA and NBL merged in
// 1949 to form the NBA. Both eras count here, matching the league's own
// record-keeping.
//
// Franchise continuity rules:
//   - Lakers:  Minneapolis -> Los Angeles
//   - Warriors: Philadelphia -> San Francisco -> Golden State
//   - Hawks:   Tri-Cities -> Milwaukee -> St. Louis -> Atlanta
//   - Kings:   Rochester Royals -> Cincinnati Royals -> KC-Omaha Kings -> KC Kings -> Sacramento
//   - 76ers:   Syracuse Nationals -> Philadelphia 76ers
//   - Pistons: Fort Wayne -> Detroit
//   - Wizards: Chicago Packers -> Chicago Zephyrs -> Baltimore Bullets (1963-73) ->
//              Capital Bullets -> Washington Bullets -> Washington Wizards
//   - Thunder: Seattle SuperSonics -> OKC Thunder
//
// The 1948 BAA champion was the ORIGINAL Baltimore Bullets (1944-54),
// a distinct franchise from the later Bullets/Wizards lineage. It uses
// its own `baltimore_bullets_og` franchiseId and never rolls up.

import type { Row } from '../../shared/types';

export const CHAMPIONS: Row[] = [
  {
    year: 1947,
    noChampion: false,
    name: 'Philadelphia Warriors',
    abbr: 'PHW',
    espnAbbr: 'gs',
    color: '#1D428A',
    franchiseId: 'warriors',
  },
  {
    year: 1948,
    noChampion: false,
    // Original Baltimore Bullets (BAA, 1944-54). Disbanded mid-1954-55
    // season; unrelated to the later Bullets/Wizards franchise. Kept on
    // its own `baltimore_bullets_og` id so it never rolls up.
    name: 'Baltimore Bullets',
    abbr: 'BAL',
    espnAbbr: null,
    color: '#002B5C',
    franchiseId: 'baltimore_bullets_og',
  },
  {
    year: 1949,
    noChampion: false,
    name: 'Minneapolis Lakers',
    abbr: 'MPL',
    espnAbbr: 'lal',
    color: '#552583',
    franchiseId: 'lakers',
  },
  {
    year: 1950,
    noChampion: false,
    name: 'Minneapolis Lakers',
    abbr: 'MPL',
    espnAbbr: 'lal',
    color: '#552583',
    franchiseId: 'lakers',
  },
  {
    year: 1951,
    noChampion: false,
    name: 'Rochester Royals',
    abbr: 'ROC',
    espnAbbr: 'sac',
    color: '#5A2D81',
    franchiseId: 'kings',
  },
  {
    year: 1952,
    noChampion: false,
    name: 'Minneapolis Lakers',
    abbr: 'MPL',
    espnAbbr: 'lal',
    color: '#552583',
    franchiseId: 'lakers',
  },
  {
    year: 1953,
    noChampion: false,
    name: 'Minneapolis Lakers',
    abbr: 'MPL',
    espnAbbr: 'lal',
    color: '#552583',
    franchiseId: 'lakers',
  },
  {
    year: 1954,
    noChampion: false,
    name: 'Minneapolis Lakers',
    abbr: 'MPL',
    espnAbbr: 'lal',
    color: '#552583',
    franchiseId: 'lakers',
  },
  {
    year: 1955,
    noChampion: false,
    name: 'Syracuse Nationals',
    abbr: 'SYR',
    espnAbbr: 'phi',
    color: '#006BB6',
    franchiseId: 'sixers',
  },
  {
    year: 1956,
    noChampion: false,
    name: 'Philadelphia Warriors',
    abbr: 'PHW',
    espnAbbr: 'gs',
    color: '#1D428A',
    franchiseId: 'warriors',
  },
  {
    year: 1957,
    noChampion: false,
    name: 'Boston Celtics',
    abbr: 'BOS',
    espnAbbr: 'bos',
    color: '#007A33',
    franchiseId: 'celtics',
  },
  {
    year: 1958,
    noChampion: false,
    name: 'St. Louis Hawks',
    abbr: 'STL',
    espnAbbr: 'atl',
    color: '#E03A3E',
    franchiseId: 'hawks',
  },
  {
    year: 1959,
    noChampion: false,
    name: 'Boston Celtics',
    abbr: 'BOS',
    espnAbbr: 'bos',
    color: '#007A33',
    franchiseId: 'celtics',
  },
  {
    year: 1960,
    noChampion: false,
    name: 'Boston Celtics',
    abbr: 'BOS',
    espnAbbr: 'bos',
    color: '#007A33',
    franchiseId: 'celtics',
  },
  {
    year: 1961,
    noChampion: false,
    name: 'Boston Celtics',
    abbr: 'BOS',
    espnAbbr: 'bos',
    color: '#007A33',
    franchiseId: 'celtics',
  },
  {
    year: 1962,
    noChampion: false,
    name: 'Boston Celtics',
    abbr: 'BOS',
    espnAbbr: 'bos',
    color: '#007A33',
    franchiseId: 'celtics',
  },
  {
    year: 1963,
    noChampion: false,
    name: 'Boston Celtics',
    abbr: 'BOS',
    espnAbbr: 'bos',
    color: '#007A33',
    franchiseId: 'celtics',
  },
  {
    year: 1964,
    noChampion: false,
    name: 'Boston Celtics',
    abbr: 'BOS',
    espnAbbr: 'bos',
    color: '#007A33',
    franchiseId: 'celtics',
  },
  {
    year: 1965,
    noChampion: false,
    name: 'Boston Celtics',
    abbr: 'BOS',
    espnAbbr: 'bos',
    color: '#007A33',
    franchiseId: 'celtics',
  },
  {
    year: 1966,
    noChampion: false,
    name: 'Boston Celtics',
    abbr: 'BOS',
    espnAbbr: 'bos',
    color: '#007A33',
    franchiseId: 'celtics',
  },
  {
    year: 1967,
    noChampion: false,
    name: 'Philadelphia 76ers',
    abbr: 'PHI',
    espnAbbr: 'phi',
    color: '#006BB6',
    franchiseId: 'sixers',
  },
  {
    year: 1968,
    noChampion: false,
    name: 'Boston Celtics',
    abbr: 'BOS',
    espnAbbr: 'bos',
    color: '#007A33',
    franchiseId: 'celtics',
  },
  {
    year: 1969,
    noChampion: false,
    name: 'Boston Celtics',
    abbr: 'BOS',
    espnAbbr: 'bos',
    color: '#007A33',
    franchiseId: 'celtics',
  },
  {
    year: 1970,
    noChampion: false,
    name: 'New York Knicks',
    abbr: 'NYK',
    espnAbbr: 'ny',
    color: '#006BB6',
    franchiseId: 'knicks',
  },
  {
    year: 1971,
    noChampion: false,
    name: 'Milwaukee Bucks',
    abbr: 'MIL',
    espnAbbr: 'mil',
    color: '#00471B',
    franchiseId: 'bucks',
  },
  {
    year: 1972,
    noChampion: false,
    name: 'Los Angeles Lakers',
    abbr: 'LAL',
    espnAbbr: 'lal',
    color: '#552583',
    franchiseId: 'lakers',
  },
  {
    year: 1973,
    noChampion: false,
    name: 'New York Knicks',
    abbr: 'NYK',
    espnAbbr: 'ny',
    color: '#006BB6',
    franchiseId: 'knicks',
  },
  {
    year: 1974,
    noChampion: false,
    name: 'Boston Celtics',
    abbr: 'BOS',
    espnAbbr: 'bos',
    color: '#007A33',
    franchiseId: 'celtics',
  },
  {
    year: 1975,
    noChampion: false,
    name: 'Golden State Warriors',
    abbr: 'GSW',
    espnAbbr: 'gs',
    color: '#1D428A',
    franchiseId: 'warriors',
  },
  {
    year: 1976,
    noChampion: false,
    name: 'Boston Celtics',
    abbr: 'BOS',
    espnAbbr: 'bos',
    color: '#007A33',
    franchiseId: 'celtics',
  },
  {
    year: 1977,
    noChampion: false,
    name: 'Portland Trail Blazers',
    abbr: 'POR',
    espnAbbr: 'por',
    color: '#E03A3E',
    franchiseId: 'blazers',
  },
  {
    year: 1978,
    noChampion: false,
    name: 'Washington Bullets',
    abbr: 'WAS',
    espnAbbr: 'wsh',
    color: '#002B5C',
    franchiseId: 'wizards',
  },
  {
    year: 1979,
    noChampion: false,
    name: 'Seattle SuperSonics',
    abbr: 'SEA',
    espnAbbr: 'okc',
    color: '#007AC1',
    franchiseId: 'thunder',
  },
  {
    year: 1980,
    noChampion: false,
    name: 'Los Angeles Lakers',
    abbr: 'LAL',
    espnAbbr: 'lal',
    color: '#552583',
    franchiseId: 'lakers',
  },
  {
    year: 1981,
    noChampion: false,
    name: 'Boston Celtics',
    abbr: 'BOS',
    espnAbbr: 'bos',
    color: '#007A33',
    franchiseId: 'celtics',
  },
  {
    year: 1982,
    noChampion: false,
    name: 'Los Angeles Lakers',
    abbr: 'LAL',
    espnAbbr: 'lal',
    color: '#552583',
    franchiseId: 'lakers',
  },
  {
    year: 1983,
    noChampion: false,
    name: 'Philadelphia 76ers',
    abbr: 'PHI',
    espnAbbr: 'phi',
    color: '#006BB6',
    franchiseId: 'sixers',
  },
  {
    year: 1984,
    noChampion: false,
    name: 'Boston Celtics',
    abbr: 'BOS',
    espnAbbr: 'bos',
    color: '#007A33',
    franchiseId: 'celtics',
  },
  {
    year: 1985,
    noChampion: false,
    name: 'Los Angeles Lakers',
    abbr: 'LAL',
    espnAbbr: 'lal',
    color: '#552583',
    franchiseId: 'lakers',
  },
  {
    year: 1986,
    noChampion: false,
    name: 'Boston Celtics',
    abbr: 'BOS',
    espnAbbr: 'bos',
    color: '#007A33',
    franchiseId: 'celtics',
  },
  {
    year: 1987,
    noChampion: false,
    name: 'Los Angeles Lakers',
    abbr: 'LAL',
    espnAbbr: 'lal',
    color: '#552583',
    franchiseId: 'lakers',
  },
  {
    year: 1988,
    noChampion: false,
    name: 'Los Angeles Lakers',
    abbr: 'LAL',
    espnAbbr: 'lal',
    color: '#552583',
    franchiseId: 'lakers',
  },
  {
    year: 1989,
    noChampion: false,
    name: 'Detroit Pistons',
    abbr: 'DET',
    espnAbbr: 'det',
    color: '#1D42BA',
    franchiseId: 'pistons',
  },
  {
    year: 1990,
    noChampion: false,
    name: 'Detroit Pistons',
    abbr: 'DET',
    espnAbbr: 'det',
    color: '#1D42BA',
    franchiseId: 'pistons',
  },
  {
    year: 1991,
    noChampion: false,
    name: 'Chicago Bulls',
    abbr: 'CHI',
    espnAbbr: 'chi',
    color: '#CE1141',
    franchiseId: 'bulls',
  },
  {
    year: 1992,
    noChampion: false,
    name: 'Chicago Bulls',
    abbr: 'CHI',
    espnAbbr: 'chi',
    color: '#CE1141',
    franchiseId: 'bulls',
  },
  {
    year: 1993,
    noChampion: false,
    name: 'Chicago Bulls',
    abbr: 'CHI',
    espnAbbr: 'chi',
    color: '#CE1141',
    franchiseId: 'bulls',
  },
  {
    year: 1994,
    noChampion: false,
    name: 'Houston Rockets',
    abbr: 'HOU',
    espnAbbr: 'hou',
    color: '#CE1141',
    franchiseId: 'rockets',
  },
  {
    year: 1995,
    noChampion: false,
    name: 'Houston Rockets',
    abbr: 'HOU',
    espnAbbr: 'hou',
    color: '#CE1141',
    franchiseId: 'rockets',
  },
  {
    year: 1996,
    noChampion: false,
    name: 'Chicago Bulls',
    abbr: 'CHI',
    espnAbbr: 'chi',
    color: '#CE1141',
    franchiseId: 'bulls',
  },
  {
    year: 1997,
    noChampion: false,
    name: 'Chicago Bulls',
    abbr: 'CHI',
    espnAbbr: 'chi',
    color: '#CE1141',
    franchiseId: 'bulls',
  },
  {
    year: 1998,
    noChampion: false,
    name: 'Chicago Bulls',
    abbr: 'CHI',
    espnAbbr: 'chi',
    color: '#CE1141',
    franchiseId: 'bulls',
  },
  {
    year: 1999,
    noChampion: false,
    name: 'San Antonio Spurs',
    abbr: 'SAS',
    espnAbbr: 'sa',
    color: '#000000',
    franchiseId: 'spurs',
  },
  {
    year: 2000,
    noChampion: false,
    name: 'Los Angeles Lakers',
    abbr: 'LAL',
    espnAbbr: 'lal',
    color: '#552583',
    franchiseId: 'lakers',
  },
  {
    year: 2001,
    noChampion: false,
    name: 'Los Angeles Lakers',
    abbr: 'LAL',
    espnAbbr: 'lal',
    color: '#552583',
    franchiseId: 'lakers',
  },
  {
    year: 2002,
    noChampion: false,
    name: 'Los Angeles Lakers',
    abbr: 'LAL',
    espnAbbr: 'lal',
    color: '#552583',
    franchiseId: 'lakers',
  },
  {
    year: 2003,
    noChampion: false,
    name: 'San Antonio Spurs',
    abbr: 'SAS',
    espnAbbr: 'sa',
    color: '#000000',
    franchiseId: 'spurs',
  },
  {
    year: 2004,
    noChampion: false,
    name: 'Detroit Pistons',
    abbr: 'DET',
    espnAbbr: 'det',
    color: '#1D42BA',
    franchiseId: 'pistons',
  },
  {
    year: 2005,
    noChampion: false,
    name: 'San Antonio Spurs',
    abbr: 'SAS',
    espnAbbr: 'sa',
    color: '#000000',
    franchiseId: 'spurs',
  },
  {
    year: 2006,
    noChampion: false,
    name: 'Miami Heat',
    abbr: 'MIA',
    espnAbbr: 'mia',
    color: '#98002E',
    franchiseId: 'heat',
  },
  {
    year: 2007,
    noChampion: false,
    name: 'San Antonio Spurs',
    abbr: 'SAS',
    espnAbbr: 'sa',
    color: '#000000',
    franchiseId: 'spurs',
  },
  {
    year: 2008,
    noChampion: false,
    name: 'Boston Celtics',
    abbr: 'BOS',
    espnAbbr: 'bos',
    color: '#007A33',
    franchiseId: 'celtics',
  },
  {
    year: 2009,
    noChampion: false,
    name: 'Los Angeles Lakers',
    abbr: 'LAL',
    espnAbbr: 'lal',
    color: '#552583',
    franchiseId: 'lakers',
  },
  {
    year: 2010,
    noChampion: false,
    name: 'Los Angeles Lakers',
    abbr: 'LAL',
    espnAbbr: 'lal',
    color: '#552583',
    franchiseId: 'lakers',
  },
  {
    year: 2011,
    noChampion: false,
    name: 'Dallas Mavericks',
    abbr: 'DAL',
    espnAbbr: 'dal',
    color: '#00538C',
    franchiseId: 'mavericks',
  },
  {
    year: 2012,
    noChampion: false,
    name: 'Miami Heat',
    abbr: 'MIA',
    espnAbbr: 'mia',
    color: '#98002E',
    franchiseId: 'heat',
  },
  {
    year: 2013,
    noChampion: false,
    name: 'Miami Heat',
    abbr: 'MIA',
    espnAbbr: 'mia',
    color: '#98002E',
    franchiseId: 'heat',
  },
  {
    year: 2014,
    noChampion: false,
    name: 'San Antonio Spurs',
    abbr: 'SAS',
    espnAbbr: 'sa',
    color: '#000000',
    franchiseId: 'spurs',
  },
  {
    year: 2015,
    noChampion: false,
    name: 'Golden State Warriors',
    abbr: 'GSW',
    espnAbbr: 'gs',
    color: '#1D428A',
    franchiseId: 'warriors',
  },
  {
    year: 2016,
    noChampion: false,
    name: 'Cleveland Cavaliers',
    abbr: 'CLE',
    espnAbbr: 'cle',
    color: '#860038',
    franchiseId: 'cavaliers',
  },
  {
    year: 2017,
    noChampion: false,
    name: 'Golden State Warriors',
    abbr: 'GSW',
    espnAbbr: 'gs',
    color: '#1D428A',
    franchiseId: 'warriors',
  },
  {
    year: 2018,
    noChampion: false,
    name: 'Golden State Warriors',
    abbr: 'GSW',
    espnAbbr: 'gs',
    color: '#1D428A',
    franchiseId: 'warriors',
  },
  {
    year: 2019,
    noChampion: false,
    name: 'Toronto Raptors',
    abbr: 'TOR',
    espnAbbr: 'tor',
    color: '#CE1141',
    franchiseId: 'raptors',
  },
  {
    year: 2020,
    noChampion: false,
    name: 'Los Angeles Lakers',
    abbr: 'LAL',
    espnAbbr: 'lal',
    color: '#552583',
    franchiseId: 'lakers',
  },
  {
    year: 2021,
    noChampion: false,
    name: 'Milwaukee Bucks',
    abbr: 'MIL',
    espnAbbr: 'mil',
    color: '#00471B',
    franchiseId: 'bucks',
  },
  {
    year: 2022,
    noChampion: false,
    name: 'Golden State Warriors',
    abbr: 'GSW',
    espnAbbr: 'gs',
    color: '#1D428A',
    franchiseId: 'warriors',
  },
  {
    year: 2023,
    noChampion: false,
    name: 'Denver Nuggets',
    abbr: 'DEN',
    espnAbbr: 'den',
    color: '#0E2240',
    franchiseId: 'nuggets',
  },
  {
    year: 2024,
    noChampion: false,
    name: 'Boston Celtics',
    abbr: 'BOS',
    espnAbbr: 'bos',
    color: '#007A33',
    franchiseId: 'celtics',
  },
  {
    year: 2025,
    noChampion: false,
    name: 'Oklahoma City Thunder',
    abbr: 'OKC',
    espnAbbr: 'okc',
    color: '#007AC1',
    franchiseId: 'thunder',
  },
];
