// Formula 1 World Constructors' Championship dataset (1958-2024).
//
// The constructors' title was instituted in 1958, eight seasons after
// the drivers' championship. Each row's champion is a TEAM, so
// `franchiseId` rolls up standard constructor lineages (Lotus across
// Climax/Ford engine eras, Red Bull across the Renault/Honda eras,
// McLaren across its Ford/TAG/Honda/Mercedes engine partners, etc.).
//
// One-off championship winners that have ambiguous lineage to a later
// rebrand are kept on their OWN franchiseId to avoid aggressive roll-up:
//   - `brawn`    (2009 only) — sold to Mercedes for 2010 but the title
//                is credited to Brawn GP as a distinct entrant.
//   - `benetton` (1995 only) — later rebranded Renault then Alpine, but
//                the constructors' trophy is Benetton Formula's.
//   - `vanwall`  (1958 only) — inaugural constructors' champion, defunct
//                shortly after; no modern successor.
//
// Contrastingly, `mclaren` (1974-2024), `ferrari`, `williams`, `lotus`,
// and `red_bull` each roll up their own continuous corporate history
// across engine partners and era renames because the teams themselves
// treat those records as continuous.
//
// `subtitle` carries the drivers' world champion FOR THAT YEAR, but only
// when that driver drove for the championship-winning constructor.
// Years where the drivers' title went to a different team leave
// `subtitle` undefined — the cross-reference back to the Drivers page
// is only meaningful when both titles went to the same entity.
//
// `espnAbbr` is null on every row for the same reason as drivers.ts:
// no reliable public logo CDN for historical F1 constructors. The text
// badge tier of TeamLogo handles display, keyed by each row's `color`.

import type { Row } from '../../shared/types';

// Shared constructor colors. Keep in sync with drivers.ts.
const COLOR_VANWALL = '#00703C';
const COLOR_FERRARI = '#DC0000';
const COLOR_MERCEDES = '#00D2BE';
const COLOR_COOPER = '#003D2C';
const COLOR_BRM = '#3C5735';
const COLOR_LOTUS = '#007940';
const COLOR_BRABHAM = '#00539C';
const COLOR_MATRA = '#1B3D8E';
const COLOR_TYRRELL = '#00308F';
const COLOR_MCLAREN = '#FF8700';
const COLOR_WILLIAMS = '#00A3E0';
const COLOR_BENETTON = '#0066CC';
const COLOR_RENAULT = '#FFF500';
const COLOR_BRAWN = '#CADE00';
const COLOR_RED_BULL = '#1E41FF';

export const CONSTRUCTORS_CHAMPIONS: Row[] = [
  {
    year: 1958,
    noChampion: false,
    // Inaugural constructors' title. Subtitle omitted: drivers' champion
    // Mike Hawthorn raced for Ferrari, not Vanwall.
    name: 'Vanwall',
    abbr: 'VAN',
    espnAbbr: null,
    color: COLOR_VANWALL,
    franchiseId: 'vanwall',
  },
  {
    year: 1959,
    noChampion: false,
    name: 'Cooper-Climax',
    abbr: 'COO',
    espnAbbr: null,
    color: COLOR_COOPER,
    franchiseId: 'cooper',
    subtitle: 'Jack Brabham',
  },
  {
    year: 1960,
    noChampion: false,
    name: 'Cooper-Climax',
    abbr: 'COO',
    espnAbbr: null,
    color: COLOR_COOPER,
    franchiseId: 'cooper',
    subtitle: 'Jack Brabham',
  },
  {
    year: 1961,
    noChampion: false,
    name: 'Ferrari',
    abbr: 'FER',
    espnAbbr: null,
    color: COLOR_FERRARI,
    franchiseId: 'ferrari',
    subtitle: 'Phil Hill',
  },
  {
    year: 1962,
    noChampion: false,
    name: 'BRM',
    abbr: 'BRM',
    espnAbbr: null,
    color: COLOR_BRM,
    franchiseId: 'brm',
    subtitle: 'Graham Hill',
  },
  {
    year: 1963,
    noChampion: false,
    name: 'Lotus-Climax',
    abbr: 'LOT',
    espnAbbr: null,
    color: COLOR_LOTUS,
    franchiseId: 'lotus',
    subtitle: 'Jim Clark',
  },
  {
    year: 1964,
    noChampion: false,
    // Both titles to Ferrari: John Surtees won drivers' for the Scuderia.
    name: 'Ferrari',
    abbr: 'FER',
    espnAbbr: null,
    color: COLOR_FERRARI,
    franchiseId: 'ferrari',
    subtitle: 'John Surtees',
  },
  {
    year: 1965,
    noChampion: false,
    name: 'Lotus-Climax',
    abbr: 'LOT',
    espnAbbr: null,
    color: COLOR_LOTUS,
    franchiseId: 'lotus',
    subtitle: 'Jim Clark',
  },
  {
    year: 1966,
    noChampion: false,
    name: 'Brabham-Repco',
    abbr: 'BRA',
    espnAbbr: null,
    color: COLOR_BRABHAM,
    franchiseId: 'brabham',
    subtitle: 'Jack Brabham',
  },
  {
    year: 1967,
    noChampion: false,
    name: 'Brabham-Repco',
    abbr: 'BRA',
    espnAbbr: null,
    color: COLOR_BRABHAM,
    franchiseId: 'brabham',
    subtitle: 'Denny Hulme',
  },
  {
    year: 1968,
    noChampion: false,
    name: 'Lotus-Ford',
    abbr: 'LOT',
    espnAbbr: null,
    color: COLOR_LOTUS,
    franchiseId: 'lotus',
    subtitle: 'Graham Hill',
  },
  {
    year: 1969,
    noChampion: false,
    name: 'Matra-Ford',
    abbr: 'MAT',
    espnAbbr: null,
    color: COLOR_MATRA,
    franchiseId: 'matra',
    subtitle: 'Jackie Stewart',
  },
  {
    year: 1970,
    noChampion: false,
    name: 'Lotus-Ford',
    abbr: 'LOT',
    espnAbbr: null,
    color: COLOR_LOTUS,
    franchiseId: 'lotus',
    subtitle: 'Jochen Rindt',
  },
  {
    year: 1971,
    noChampion: false,
    name: 'Tyrrell-Ford',
    abbr: 'TYR',
    espnAbbr: null,
    color: COLOR_TYRRELL,
    franchiseId: 'tyrrell',
    subtitle: 'Jackie Stewart',
  },
  {
    year: 1972,
    noChampion: false,
    name: 'Lotus-Ford',
    abbr: 'LOT',
    espnAbbr: null,
    color: COLOR_LOTUS,
    franchiseId: 'lotus',
    subtitle: 'Emerson Fittipaldi',
  },
  {
    year: 1973,
    noChampion: false,
    // Subtitle omitted: drivers' champion Jackie Stewart drove for Tyrrell.
    name: 'Lotus-Ford',
    abbr: 'LOT',
    espnAbbr: null,
    color: COLOR_LOTUS,
    franchiseId: 'lotus',
  },
  {
    year: 1974,
    noChampion: false,
    name: 'McLaren-Ford',
    abbr: 'MCL',
    espnAbbr: null,
    color: COLOR_MCLAREN,
    franchiseId: 'mclaren',
    subtitle: 'Emerson Fittipaldi',
  },
  {
    year: 1975,
    noChampion: false,
    name: 'Ferrari',
    abbr: 'FER',
    espnAbbr: null,
    color: COLOR_FERRARI,
    franchiseId: 'ferrari',
    subtitle: 'Niki Lauda',
  },
  {
    year: 1976,
    noChampion: false,
    // Subtitle omitted: drivers' champion James Hunt drove for McLaren.
    name: 'Ferrari',
    abbr: 'FER',
    espnAbbr: null,
    color: COLOR_FERRARI,
    franchiseId: 'ferrari',
  },
  {
    year: 1977,
    noChampion: false,
    name: 'Ferrari',
    abbr: 'FER',
    espnAbbr: null,
    color: COLOR_FERRARI,
    franchiseId: 'ferrari',
    subtitle: 'Niki Lauda',
  },
  {
    year: 1978,
    noChampion: false,
    name: 'Lotus-Ford',
    abbr: 'LOT',
    espnAbbr: null,
    color: COLOR_LOTUS,
    franchiseId: 'lotus',
    subtitle: 'Mario Andretti',
  },
  {
    year: 1979,
    noChampion: false,
    name: 'Ferrari',
    abbr: 'FER',
    espnAbbr: null,
    color: COLOR_FERRARI,
    franchiseId: 'ferrari',
    subtitle: 'Jody Scheckter',
  },
  {
    year: 1980,
    noChampion: false,
    name: 'Williams-Ford',
    abbr: 'WIL',
    espnAbbr: null,
    color: COLOR_WILLIAMS,
    franchiseId: 'williams',
    subtitle: 'Alan Jones',
  },
  {
    year: 1981,
    noChampion: false,
    // Subtitle omitted: Piquet won drivers' for Brabham, not Williams.
    name: 'Williams-Ford',
    abbr: 'WIL',
    espnAbbr: null,
    color: COLOR_WILLIAMS,
    franchiseId: 'williams',
  },
  {
    year: 1982,
    noChampion: false,
    // Subtitle omitted: Keke Rosberg won drivers' for Williams, not Ferrari.
    name: 'Ferrari',
    abbr: 'FER',
    espnAbbr: null,
    color: COLOR_FERRARI,
    franchiseId: 'ferrari',
  },
  {
    year: 1983,
    noChampion: false,
    // Subtitle omitted: Piquet won drivers' for Brabham, not Ferrari.
    name: 'Ferrari',
    abbr: 'FER',
    espnAbbr: null,
    color: COLOR_FERRARI,
    franchiseId: 'ferrari',
  },
  {
    year: 1984,
    noChampion: false,
    name: 'McLaren-TAG',
    abbr: 'MCL',
    espnAbbr: null,
    color: COLOR_MCLAREN,
    franchiseId: 'mclaren',
    subtitle: 'Niki Lauda',
  },
  {
    year: 1985,
    noChampion: false,
    name: 'McLaren-TAG',
    abbr: 'MCL',
    espnAbbr: null,
    color: COLOR_MCLAREN,
    franchiseId: 'mclaren',
    subtitle: 'Alain Prost',
  },
  {
    year: 1986,
    noChampion: false,
    // Subtitle omitted: Prost won drivers' for McLaren, not Williams.
    name: 'Williams-Honda',
    abbr: 'WIL',
    espnAbbr: null,
    color: COLOR_WILLIAMS,
    franchiseId: 'williams',
  },
  {
    year: 1987,
    noChampion: false,
    name: 'Williams-Honda',
    abbr: 'WIL',
    espnAbbr: null,
    color: COLOR_WILLIAMS,
    franchiseId: 'williams',
    subtitle: 'Nelson Piquet',
  },
  {
    year: 1988,
    noChampion: false,
    name: 'McLaren-Honda',
    abbr: 'MCL',
    espnAbbr: null,
    color: COLOR_MCLAREN,
    franchiseId: 'mclaren',
    subtitle: 'Ayrton Senna',
  },
  {
    year: 1989,
    noChampion: false,
    name: 'McLaren-Honda',
    abbr: 'MCL',
    espnAbbr: null,
    color: COLOR_MCLAREN,
    franchiseId: 'mclaren',
    subtitle: 'Alain Prost',
  },
  {
    year: 1990,
    noChampion: false,
    name: 'McLaren-Honda',
    abbr: 'MCL',
    espnAbbr: null,
    color: COLOR_MCLAREN,
    franchiseId: 'mclaren',
    subtitle: 'Ayrton Senna',
  },
  {
    year: 1991,
    noChampion: false,
    name: 'McLaren-Honda',
    abbr: 'MCL',
    espnAbbr: null,
    color: COLOR_MCLAREN,
    franchiseId: 'mclaren',
    subtitle: 'Ayrton Senna',
  },
  {
    year: 1992,
    noChampion: false,
    name: 'Williams-Renault',
    abbr: 'WIL',
    espnAbbr: null,
    color: COLOR_WILLIAMS,
    franchiseId: 'williams',
    subtitle: 'Nigel Mansell',
  },
  {
    year: 1993,
    noChampion: false,
    name: 'Williams-Renault',
    abbr: 'WIL',
    espnAbbr: null,
    color: COLOR_WILLIAMS,
    franchiseId: 'williams',
    subtitle: 'Alain Prost',
  },
  {
    year: 1994,
    noChampion: false,
    // Subtitle omitted: Schumacher won drivers' for Benetton, not Williams.
    name: 'Williams-Renault',
    abbr: 'WIL',
    espnAbbr: null,
    color: COLOR_WILLIAMS,
    franchiseId: 'williams',
  },
  {
    year: 1995,
    noChampion: false,
    // Benetton Formula kept on its own franchiseId despite later being
    // rebranded Renault/Alpine — the 1995 trophy is Benetton's record.
    name: 'Benetton-Renault',
    abbr: 'BEN',
    espnAbbr: null,
    color: COLOR_BENETTON,
    franchiseId: 'benetton',
    subtitle: 'Michael Schumacher',
  },
  {
    year: 1996,
    noChampion: false,
    name: 'Williams-Renault',
    abbr: 'WIL',
    espnAbbr: null,
    color: COLOR_WILLIAMS,
    franchiseId: 'williams',
    subtitle: 'Damon Hill',
  },
  {
    year: 1997,
    noChampion: false,
    name: 'Williams-Renault',
    abbr: 'WIL',
    espnAbbr: null,
    color: COLOR_WILLIAMS,
    franchiseId: 'williams',
    subtitle: 'Jacques Villeneuve',
  },
  {
    year: 1998,
    noChampion: false,
    name: 'McLaren-Mercedes',
    abbr: 'MCL',
    espnAbbr: null,
    color: COLOR_MCLAREN,
    franchiseId: 'mclaren',
    subtitle: 'Mika H\u00e4kkinen',
  },
  {
    year: 1999,
    noChampion: false,
    // Subtitle omitted: H\u00e4kkinen won drivers' for McLaren, not Ferrari.
    name: 'Ferrari',
    abbr: 'FER',
    espnAbbr: null,
    color: COLOR_FERRARI,
    franchiseId: 'ferrari',
  },
  {
    year: 2000,
    noChampion: false,
    name: 'Ferrari',
    abbr: 'FER',
    espnAbbr: null,
    color: COLOR_FERRARI,
    franchiseId: 'ferrari',
    subtitle: 'Michael Schumacher',
  },
  {
    year: 2001,
    noChampion: false,
    name: 'Ferrari',
    abbr: 'FER',
    espnAbbr: null,
    color: COLOR_FERRARI,
    franchiseId: 'ferrari',
    subtitle: 'Michael Schumacher',
  },
  {
    year: 2002,
    noChampion: false,
    name: 'Ferrari',
    abbr: 'FER',
    espnAbbr: null,
    color: COLOR_FERRARI,
    franchiseId: 'ferrari',
    subtitle: 'Michael Schumacher',
  },
  {
    year: 2003,
    noChampion: false,
    name: 'Ferrari',
    abbr: 'FER',
    espnAbbr: null,
    color: COLOR_FERRARI,
    franchiseId: 'ferrari',
    subtitle: 'Michael Schumacher',
  },
  {
    year: 2004,
    noChampion: false,
    name: 'Ferrari',
    abbr: 'FER',
    espnAbbr: null,
    color: COLOR_FERRARI,
    franchiseId: 'ferrari',
    subtitle: 'Michael Schumacher',
  },
  {
    year: 2005,
    noChampion: false,
    // Renault F1 Team — distinct entity from the 1995 Benetton-Renault
    // engine partnership. Benetton had been rebranded Renault F1 by now,
    // but we keep `renault` as a separate franchiseId per the spec.
    name: 'Renault',
    abbr: 'REN',
    espnAbbr: null,
    color: COLOR_RENAULT,
    franchiseId: 'renault',
    subtitle: 'Fernando Alonso',
  },
  {
    year: 2006,
    noChampion: false,
    name: 'Renault',
    abbr: 'REN',
    espnAbbr: null,
    color: COLOR_RENAULT,
    franchiseId: 'renault',
    subtitle: 'Fernando Alonso',
  },
  {
    year: 2007,
    noChampion: false,
    // Both titles to Ferrari: R\u00e4ikk\u00f6nen won drivers' for the Scuderia.
    name: 'Ferrari',
    abbr: 'FER',
    espnAbbr: null,
    color: COLOR_FERRARI,
    franchiseId: 'ferrari',
    subtitle: 'Kimi R\u00e4ikk\u00f6nen',
  },
  {
    year: 2008,
    noChampion: false,
    // Subtitle omitted: Hamilton won drivers' for McLaren, not Ferrari.
    name: 'Ferrari',
    abbr: 'FER',
    espnAbbr: null,
    color: COLOR_FERRARI,
    franchiseId: 'ferrari',
  },
  {
    year: 2009,
    noChampion: false,
    // Brawn GP: one-season-only champion entrant. Sold to Mercedes for
    // 2010 but the title record stays with Brawn's own franchiseId.
    name: 'Brawn-Mercedes',
    abbr: 'BGP',
    espnAbbr: null,
    color: COLOR_BRAWN,
    franchiseId: 'brawn',
    subtitle: 'Jenson Button',
  },
  {
    year: 2010,
    noChampion: false,
    name: 'Red Bull-Renault',
    abbr: 'RBR',
    espnAbbr: null,
    color: COLOR_RED_BULL,
    franchiseId: 'red_bull',
    subtitle: 'Sebastian Vettel',
  },
  {
    year: 2011,
    noChampion: false,
    name: 'Red Bull-Renault',
    abbr: 'RBR',
    espnAbbr: null,
    color: COLOR_RED_BULL,
    franchiseId: 'red_bull',
    subtitle: 'Sebastian Vettel',
  },
  {
    year: 2012,
    noChampion: false,
    name: 'Red Bull-Renault',
    abbr: 'RBR',
    espnAbbr: null,
    color: COLOR_RED_BULL,
    franchiseId: 'red_bull',
    subtitle: 'Sebastian Vettel',
  },
  {
    year: 2013,
    noChampion: false,
    name: 'Red Bull-Renault',
    abbr: 'RBR',
    espnAbbr: null,
    color: COLOR_RED_BULL,
    franchiseId: 'red_bull',
    subtitle: 'Sebastian Vettel',
  },
  {
    year: 2014,
    noChampion: false,
    name: 'Mercedes',
    abbr: 'MER',
    espnAbbr: null,
    color: COLOR_MERCEDES,
    franchiseId: 'mercedes',
    subtitle: 'Lewis Hamilton',
  },
  {
    year: 2015,
    noChampion: false,
    name: 'Mercedes',
    abbr: 'MER',
    espnAbbr: null,
    color: COLOR_MERCEDES,
    franchiseId: 'mercedes',
    subtitle: 'Lewis Hamilton',
  },
  {
    year: 2016,
    noChampion: false,
    name: 'Mercedes',
    abbr: 'MER',
    espnAbbr: null,
    color: COLOR_MERCEDES,
    franchiseId: 'mercedes',
    subtitle: 'Nico Rosberg',
  },
  {
    year: 2017,
    noChampion: false,
    name: 'Mercedes',
    abbr: 'MER',
    espnAbbr: null,
    color: COLOR_MERCEDES,
    franchiseId: 'mercedes',
    subtitle: 'Lewis Hamilton',
  },
  {
    year: 2018,
    noChampion: false,
    name: 'Mercedes',
    abbr: 'MER',
    espnAbbr: null,
    color: COLOR_MERCEDES,
    franchiseId: 'mercedes',
    subtitle: 'Lewis Hamilton',
  },
  {
    year: 2019,
    noChampion: false,
    name: 'Mercedes',
    abbr: 'MER',
    espnAbbr: null,
    color: COLOR_MERCEDES,
    franchiseId: 'mercedes',
    subtitle: 'Lewis Hamilton',
  },
  {
    year: 2020,
    noChampion: false,
    name: 'Mercedes',
    abbr: 'MER',
    espnAbbr: null,
    color: COLOR_MERCEDES,
    franchiseId: 'mercedes',
    subtitle: 'Lewis Hamilton',
  },
  {
    year: 2021,
    noChampion: false,
    // Subtitle omitted: Verstappen won drivers' for Red Bull, not Mercedes.
    name: 'Mercedes',
    abbr: 'MER',
    espnAbbr: null,
    color: COLOR_MERCEDES,
    franchiseId: 'mercedes',
  },
  {
    year: 2022,
    noChampion: false,
    name: 'Red Bull Racing',
    abbr: 'RBR',
    espnAbbr: null,
    color: COLOR_RED_BULL,
    franchiseId: 'red_bull',
    subtitle: 'Max Verstappen',
  },
  {
    year: 2023,
    noChampion: false,
    name: 'Red Bull Racing',
    abbr: 'RBR',
    espnAbbr: null,
    color: COLOR_RED_BULL,
    franchiseId: 'red_bull',
    subtitle: 'Max Verstappen',
  },
  {
    year: 2024,
    noChampion: false,
    // McLaren's first constructors' title since 1998. Subtitle omitted:
    // Verstappen won drivers' for Red Bull.
    name: 'McLaren-Mercedes',
    abbr: 'MCL',
    espnAbbr: null,
    color: COLOR_MCLAREN,
    franchiseId: 'mclaren',
  },
];
