// Formula 1 World Drivers' Championship dataset (1950-2024).
//
// Unlike the team-sport configs in this project, F1 Drivers treats the
// INDIVIDUAL DRIVER as the championship-winning entity. `franchiseId` is
// therefore a per-driver slug (lastname_firstname, ASCII-folded), so the
// running-total rollup tracks career world championships rather than team
// titles. `subtitle` carries the constructor the driver raced for that
// season, which the ChampionRow surfaces below the name and cross-
// references the sibling Constructors page (/f1/constructors).
//
// `color` is the constructor's primary color for that year so the row's
// accent reads as a team color even though the championship is personal.
// Hex values are shared with src/sports/f1/constructors.ts to keep the
// two pages visually consistent.
//
// `espnAbbr` is null for every row — F1 has no reliable public logo CDN
// for the historical constructor names, so the TeamLogo cascade falls
// straight through to the color-filled text badge. That is expected and
// is the design for this first F1 release.
//
// Driver `abbr` uses the modern FIA 3-letter code where one is well
// established (HAM, VER, MSC, etc.) and short initials/mnemonics where
// not. The text badge also shows the driver name, so the abbreviation
// only has to be stable, not globally unique.

import type { Row } from '../../shared/types';

// Shared constructor colors. Keep in sync with constructors.ts.
const COLOR_ALFA_ROMEO = '#860018';
const COLOR_FERRARI = '#DC0000';
const COLOR_MERCEDES = '#00D2BE';
const COLOR_MASERATI = '#0A1A3A';
const COLOR_COOPER = '#003D2C';
const COLOR_BRM = '#3C5735';
const COLOR_LOTUS = '#007940';
const COLOR_BRABHAM = '#00539C';
const COLOR_MATRA = '#1B3D8E';
const COLOR_TYRRELL = '#00308F';
const COLOR_MCLAREN = '#FF8700';
const COLOR_WILLIAMS = '#00A3E0';
const COLOR_BENETTON = '#0066CC';
const COLOR_RENAULT = '#FFF500';
const COLOR_BRAWN = '#CADE00';
const COLOR_RED_BULL = '#1E41FF';

export const DRIVERS_CHAMPIONS: Row[] = [
  {
    year: 1950,
    noChampion: false,
    name: 'Giuseppe Farina',
    abbr: 'FAR',
    espnAbbr: null,
    color: COLOR_ALFA_ROMEO,
    franchiseId: 'farina_giuseppe',
    subtitle: 'Alfa Romeo',
  },
  {
    year: 1951,
    noChampion: false,
    name: 'Juan Manuel Fangio',
    abbr: 'FAN',
    espnAbbr: null,
    color: COLOR_ALFA_ROMEO,
    franchiseId: 'fangio_juan_manuel',
    subtitle: 'Alfa Romeo',
  },
  {
    year: 1952,
    noChampion: false,
    name: 'Alberto Ascari',
    abbr: 'ASC',
    espnAbbr: null,
    color: COLOR_FERRARI,
    franchiseId: 'ascari_alberto',
    subtitle: 'Ferrari',
  },
  {
    year: 1953,
    noChampion: false,
    name: 'Alberto Ascari',
    abbr: 'ASC',
    espnAbbr: null,
    color: COLOR_FERRARI,
    franchiseId: 'ascari_alberto',
    subtitle: 'Ferrari',
  },
  {
    year: 1954,
    noChampion: false,
    // Fangio drove for both Maserati (early 1954) and Mercedes-Benz (mid-
    // season onward); the FIA credits the title team as Mercedes.
    name: 'Juan Manuel Fangio',
    abbr: 'FAN',
    espnAbbr: null,
    color: COLOR_MERCEDES,
    franchiseId: 'fangio_juan_manuel',
    subtitle: 'Mercedes',
  },
  {
    year: 1955,
    noChampion: false,
    name: 'Juan Manuel Fangio',
    abbr: 'FAN',
    espnAbbr: null,
    color: COLOR_MERCEDES,
    franchiseId: 'fangio_juan_manuel',
    subtitle: 'Mercedes',
  },
  {
    year: 1956,
    noChampion: false,
    name: 'Juan Manuel Fangio',
    abbr: 'FAN',
    espnAbbr: null,
    color: COLOR_FERRARI,
    franchiseId: 'fangio_juan_manuel',
    subtitle: 'Ferrari',
  },
  {
    year: 1957,
    noChampion: false,
    name: 'Juan Manuel Fangio',
    abbr: 'FAN',
    espnAbbr: null,
    color: COLOR_MASERATI,
    franchiseId: 'fangio_juan_manuel',
    subtitle: 'Maserati',
  },
  {
    year: 1958,
    noChampion: false,
    name: 'Mike Hawthorn',
    abbr: 'HAW',
    espnAbbr: null,
    color: COLOR_FERRARI,
    franchiseId: 'hawthorn_mike',
    subtitle: 'Ferrari',
  },
  {
    year: 1959,
    noChampion: false,
    name: 'Jack Brabham',
    abbr: 'BRA',
    espnAbbr: null,
    color: COLOR_COOPER,
    franchiseId: 'brabham_jack',
    subtitle: 'Cooper-Climax',
  },
  {
    year: 1960,
    noChampion: false,
    name: 'Jack Brabham',
    abbr: 'BRA',
    espnAbbr: null,
    color: COLOR_COOPER,
    franchiseId: 'brabham_jack',
    subtitle: 'Cooper-Climax',
  },
  {
    year: 1961,
    noChampion: false,
    // American Phil Hill (1961); distinct franchiseId from British Graham
    // Hill (1962, 1968) and Damon Hill (1996).
    name: 'Phil Hill',
    abbr: 'HIL',
    espnAbbr: null,
    color: COLOR_FERRARI,
    franchiseId: 'hill_phil',
    subtitle: 'Ferrari',
  },
  {
    year: 1962,
    noChampion: false,
    name: 'Graham Hill',
    abbr: 'HIL',
    espnAbbr: null,
    color: COLOR_BRM,
    franchiseId: 'hill_graham',
    subtitle: 'BRM',
  },
  {
    year: 1963,
    noChampion: false,
    name: 'Jim Clark',
    abbr: 'CLA',
    espnAbbr: null,
    color: COLOR_LOTUS,
    franchiseId: 'clark_jim',
    subtitle: 'Lotus-Climax',
  },
  {
    year: 1964,
    noChampion: false,
    name: 'John Surtees',
    abbr: 'SUR',
    espnAbbr: null,
    color: COLOR_FERRARI,
    franchiseId: 'surtees_john',
    subtitle: 'Ferrari',
  },
  {
    year: 1965,
    noChampion: false,
    name: 'Jim Clark',
    abbr: 'CLA',
    espnAbbr: null,
    color: COLOR_LOTUS,
    franchiseId: 'clark_jim',
    subtitle: 'Lotus-Climax',
  },
  {
    year: 1966,
    noChampion: false,
    name: 'Jack Brabham',
    abbr: 'BRA',
    espnAbbr: null,
    color: COLOR_BRABHAM,
    franchiseId: 'brabham_jack',
    subtitle: 'Brabham-Repco',
  },
  {
    year: 1967,
    noChampion: false,
    name: 'Denny Hulme',
    abbr: 'HUL',
    espnAbbr: null,
    color: COLOR_BRABHAM,
    franchiseId: 'hulme_denny',
    subtitle: 'Brabham-Repco',
  },
  {
    year: 1968,
    noChampion: false,
    name: 'Graham Hill',
    abbr: 'HIL',
    espnAbbr: null,
    color: COLOR_LOTUS,
    franchiseId: 'hill_graham',
    subtitle: 'Lotus-Ford',
  },
  {
    year: 1969,
    noChampion: false,
    name: 'Jackie Stewart',
    abbr: 'STE',
    espnAbbr: null,
    color: COLOR_MATRA,
    franchiseId: 'stewart_jackie',
    subtitle: 'Matra-Ford',
  },
  {
    year: 1970,
    noChampion: false,
    // Posthumous champion: Rindt was killed in qualifying at Monza and
    // no challenger could catch his points total over the remaining rounds.
    name: 'Jochen Rindt',
    abbr: 'RIN',
    espnAbbr: null,
    color: COLOR_LOTUS,
    franchiseId: 'rindt_jochen',
    subtitle: 'Lotus-Ford',
  },
  {
    year: 1971,
    noChampion: false,
    name: 'Jackie Stewart',
    abbr: 'STE',
    espnAbbr: null,
    color: COLOR_TYRRELL,
    franchiseId: 'stewart_jackie',
    subtitle: 'Tyrrell-Ford',
  },
  {
    year: 1972,
    noChampion: false,
    name: 'Emerson Fittipaldi',
    abbr: 'FIT',
    espnAbbr: null,
    color: COLOR_LOTUS,
    franchiseId: 'fittipaldi_emerson',
    subtitle: 'Lotus-Ford',
  },
  {
    year: 1973,
    noChampion: false,
    name: 'Jackie Stewart',
    abbr: 'STE',
    espnAbbr: null,
    color: COLOR_TYRRELL,
    franchiseId: 'stewart_jackie',
    subtitle: 'Tyrrell-Ford',
  },
  {
    year: 1974,
    noChampion: false,
    name: 'Emerson Fittipaldi',
    abbr: 'FIT',
    espnAbbr: null,
    color: COLOR_MCLAREN,
    franchiseId: 'fittipaldi_emerson',
    subtitle: 'McLaren-Ford',
  },
  {
    year: 1975,
    noChampion: false,
    name: 'Niki Lauda',
    abbr: 'LAU',
    espnAbbr: null,
    color: COLOR_FERRARI,
    franchiseId: 'lauda_niki',
    subtitle: 'Ferrari',
  },
  {
    year: 1976,
    noChampion: false,
    name: 'James Hunt',
    abbr: 'HUN',
    espnAbbr: null,
    color: COLOR_MCLAREN,
    franchiseId: 'hunt_james',
    subtitle: 'McLaren-Ford',
  },
  {
    year: 1977,
    noChampion: false,
    name: 'Niki Lauda',
    abbr: 'LAU',
    espnAbbr: null,
    color: COLOR_FERRARI,
    franchiseId: 'lauda_niki',
    subtitle: 'Ferrari',
  },
  {
    year: 1978,
    noChampion: false,
    name: 'Mario Andretti',
    abbr: 'AND',
    espnAbbr: null,
    color: COLOR_LOTUS,
    franchiseId: 'andretti_mario',
    subtitle: 'Lotus-Ford',
  },
  {
    year: 1979,
    noChampion: false,
    name: 'Jody Scheckter',
    abbr: 'SCH',
    espnAbbr: null,
    color: COLOR_FERRARI,
    franchiseId: 'scheckter_jody',
    subtitle: 'Ferrari',
  },
  {
    year: 1980,
    noChampion: false,
    name: 'Alan Jones',
    abbr: 'JON',
    espnAbbr: null,
    color: COLOR_WILLIAMS,
    franchiseId: 'jones_alan',
    subtitle: 'Williams-Ford',
  },
  {
    year: 1981,
    noChampion: false,
    name: 'Nelson Piquet',
    abbr: 'PIQ',
    espnAbbr: null,
    color: COLOR_BRABHAM,
    franchiseId: 'piquet_nelson',
    subtitle: 'Brabham-Ford',
  },
  {
    year: 1982,
    noChampion: false,
    // Keke Rosberg (father); distinct franchiseId from son Nico (2016).
    name: 'Keke Rosberg',
    abbr: 'ROS',
    espnAbbr: null,
    color: COLOR_WILLIAMS,
    franchiseId: 'rosberg_keke',
    subtitle: 'Williams-Ford',
  },
  {
    year: 1983,
    noChampion: false,
    name: 'Nelson Piquet',
    abbr: 'PIQ',
    espnAbbr: null,
    color: COLOR_BRABHAM,
    franchiseId: 'piquet_nelson',
    subtitle: 'Brabham-BMW',
  },
  {
    year: 1984,
    noChampion: false,
    name: 'Niki Lauda',
    abbr: 'LAU',
    espnAbbr: null,
    color: COLOR_MCLAREN,
    franchiseId: 'lauda_niki',
    subtitle: 'McLaren-TAG',
  },
  {
    year: 1985,
    noChampion: false,
    name: 'Alain Prost',
    abbr: 'PRO',
    espnAbbr: null,
    color: COLOR_MCLAREN,
    franchiseId: 'prost_alain',
    subtitle: 'McLaren-TAG',
  },
  {
    year: 1986,
    noChampion: false,
    name: 'Alain Prost',
    abbr: 'PRO',
    espnAbbr: null,
    color: COLOR_MCLAREN,
    franchiseId: 'prost_alain',
    subtitle: 'McLaren-TAG',
  },
  {
    year: 1987,
    noChampion: false,
    name: 'Nelson Piquet',
    abbr: 'PIQ',
    espnAbbr: null,
    color: COLOR_WILLIAMS,
    franchiseId: 'piquet_nelson',
    subtitle: 'Williams-Honda',
  },
  {
    year: 1988,
    noChampion: false,
    name: 'Ayrton Senna',
    abbr: 'SEN',
    espnAbbr: null,
    color: COLOR_MCLAREN,
    franchiseId: 'senna_ayrton',
    subtitle: 'McLaren-Honda',
  },
  {
    year: 1989,
    noChampion: false,
    name: 'Alain Prost',
    abbr: 'PRO',
    espnAbbr: null,
    color: COLOR_MCLAREN,
    franchiseId: 'prost_alain',
    subtitle: 'McLaren-Honda',
  },
  {
    year: 1990,
    noChampion: false,
    name: 'Ayrton Senna',
    abbr: 'SEN',
    espnAbbr: null,
    color: COLOR_MCLAREN,
    franchiseId: 'senna_ayrton',
    subtitle: 'McLaren-Honda',
  },
  {
    year: 1991,
    noChampion: false,
    name: 'Ayrton Senna',
    abbr: 'SEN',
    espnAbbr: null,
    color: COLOR_MCLAREN,
    franchiseId: 'senna_ayrton',
    subtitle: 'McLaren-Honda',
  },
  {
    year: 1992,
    noChampion: false,
    name: 'Nigel Mansell',
    abbr: 'MAN',
    espnAbbr: null,
    color: COLOR_WILLIAMS,
    franchiseId: 'mansell_nigel',
    subtitle: 'Williams-Renault',
  },
  {
    year: 1993,
    noChampion: false,
    name: 'Alain Prost',
    abbr: 'PRO',
    espnAbbr: null,
    color: COLOR_WILLIAMS,
    franchiseId: 'prost_alain',
    subtitle: 'Williams-Renault',
  },
  {
    year: 1994,
    noChampion: false,
    name: 'Michael Schumacher',
    abbr: 'MSC',
    espnAbbr: null,
    color: COLOR_BENETTON,
    franchiseId: 'schumacher_michael',
    subtitle: 'Benetton-Ford',
  },
  {
    year: 1995,
    noChampion: false,
    name: 'Michael Schumacher',
    abbr: 'MSC',
    espnAbbr: null,
    color: COLOR_BENETTON,
    franchiseId: 'schumacher_michael',
    subtitle: 'Benetton-Renault',
  },
  {
    year: 1996,
    noChampion: false,
    // Damon Hill (son of Graham); distinct franchiseId from Graham/Phil.
    name: 'Damon Hill',
    abbr: 'DAH',
    espnAbbr: null,
    color: COLOR_WILLIAMS,
    franchiseId: 'hill_damon',
    subtitle: 'Williams-Renault',
  },
  {
    year: 1997,
    noChampion: false,
    name: 'Jacques Villeneuve',
    abbr: 'VIL',
    espnAbbr: null,
    color: COLOR_WILLIAMS,
    franchiseId: 'villeneuve_jacques',
    subtitle: 'Williams-Renault',
  },
  {
    year: 1998,
    noChampion: false,
    name: 'Mika H\u00e4kkinen',
    abbr: 'HAK',
    espnAbbr: null,
    color: COLOR_MCLAREN,
    franchiseId: 'hakkinen_mika',
    subtitle: 'McLaren-Mercedes',
  },
  {
    year: 1999,
    noChampion: false,
    name: 'Mika H\u00e4kkinen',
    abbr: 'HAK',
    espnAbbr: null,
    color: COLOR_MCLAREN,
    franchiseId: 'hakkinen_mika',
    subtitle: 'McLaren-Mercedes',
  },
  {
    year: 2000,
    noChampion: false,
    name: 'Michael Schumacher',
    abbr: 'MSC',
    espnAbbr: null,
    color: COLOR_FERRARI,
    franchiseId: 'schumacher_michael',
    subtitle: 'Ferrari',
  },
  {
    year: 2001,
    noChampion: false,
    name: 'Michael Schumacher',
    abbr: 'MSC',
    espnAbbr: null,
    color: COLOR_FERRARI,
    franchiseId: 'schumacher_michael',
    subtitle: 'Ferrari',
  },
  {
    year: 2002,
    noChampion: false,
    name: 'Michael Schumacher',
    abbr: 'MSC',
    espnAbbr: null,
    color: COLOR_FERRARI,
    franchiseId: 'schumacher_michael',
    subtitle: 'Ferrari',
  },
  {
    year: 2003,
    noChampion: false,
    name: 'Michael Schumacher',
    abbr: 'MSC',
    espnAbbr: null,
    color: COLOR_FERRARI,
    franchiseId: 'schumacher_michael',
    subtitle: 'Ferrari',
  },
  {
    year: 2004,
    noChampion: false,
    name: 'Michael Schumacher',
    abbr: 'MSC',
    espnAbbr: null,
    color: COLOR_FERRARI,
    franchiseId: 'schumacher_michael',
    subtitle: 'Ferrari',
  },
  {
    year: 2005,
    noChampion: false,
    name: 'Fernando Alonso',
    abbr: 'ALO',
    espnAbbr: null,
    color: COLOR_RENAULT,
    franchiseId: 'alonso_fernando',
    subtitle: 'Renault',
  },
  {
    year: 2006,
    noChampion: false,
    name: 'Fernando Alonso',
    abbr: 'ALO',
    espnAbbr: null,
    color: COLOR_RENAULT,
    franchiseId: 'alonso_fernando',
    subtitle: 'Renault',
  },
  {
    year: 2007,
    noChampion: false,
    name: 'Kimi R\u00e4ikk\u00f6nen',
    abbr: 'RAI',
    espnAbbr: null,
    color: COLOR_FERRARI,
    franchiseId: 'raikkonen_kimi',
    subtitle: 'Ferrari',
  },
  {
    year: 2008,
    noChampion: false,
    name: 'Lewis Hamilton',
    abbr: 'HAM',
    espnAbbr: null,
    color: COLOR_MCLAREN,
    franchiseId: 'hamilton_lewis',
    subtitle: 'McLaren-Mercedes',
  },
  {
    year: 2009,
    noChampion: false,
    name: 'Jenson Button',
    abbr: 'BUT',
    espnAbbr: null,
    color: COLOR_BRAWN,
    franchiseId: 'button_jenson',
    subtitle: 'Brawn-Mercedes',
  },
  {
    year: 2010,
    noChampion: false,
    name: 'Sebastian Vettel',
    abbr: 'VET',
    espnAbbr: null,
    color: COLOR_RED_BULL,
    franchiseId: 'vettel_sebastian',
    subtitle: 'Red Bull-Renault',
  },
  {
    year: 2011,
    noChampion: false,
    name: 'Sebastian Vettel',
    abbr: 'VET',
    espnAbbr: null,
    color: COLOR_RED_BULL,
    franchiseId: 'vettel_sebastian',
    subtitle: 'Red Bull-Renault',
  },
  {
    year: 2012,
    noChampion: false,
    name: 'Sebastian Vettel',
    abbr: 'VET',
    espnAbbr: null,
    color: COLOR_RED_BULL,
    franchiseId: 'vettel_sebastian',
    subtitle: 'Red Bull-Renault',
  },
  {
    year: 2013,
    noChampion: false,
    name: 'Sebastian Vettel',
    abbr: 'VET',
    espnAbbr: null,
    color: COLOR_RED_BULL,
    franchiseId: 'vettel_sebastian',
    subtitle: 'Red Bull-Renault',
  },
  {
    year: 2014,
    noChampion: false,
    name: 'Lewis Hamilton',
    abbr: 'HAM',
    espnAbbr: null,
    color: COLOR_MERCEDES,
    franchiseId: 'hamilton_lewis',
    subtitle: 'Mercedes',
  },
  {
    year: 2015,
    noChampion: false,
    name: 'Lewis Hamilton',
    abbr: 'HAM',
    espnAbbr: null,
    color: COLOR_MERCEDES,
    franchiseId: 'hamilton_lewis',
    subtitle: 'Mercedes',
  },
  {
    year: 2016,
    noChampion: false,
    // Nico Rosberg (son of Keke); distinct franchiseId.
    name: 'Nico Rosberg',
    abbr: 'ROS',
    espnAbbr: null,
    color: COLOR_MERCEDES,
    franchiseId: 'rosberg_nico',
    subtitle: 'Mercedes',
  },
  {
    year: 2017,
    noChampion: false,
    name: 'Lewis Hamilton',
    abbr: 'HAM',
    espnAbbr: null,
    color: COLOR_MERCEDES,
    franchiseId: 'hamilton_lewis',
    subtitle: 'Mercedes',
  },
  {
    year: 2018,
    noChampion: false,
    name: 'Lewis Hamilton',
    abbr: 'HAM',
    espnAbbr: null,
    color: COLOR_MERCEDES,
    franchiseId: 'hamilton_lewis',
    subtitle: 'Mercedes',
  },
  {
    year: 2019,
    noChampion: false,
    name: 'Lewis Hamilton',
    abbr: 'HAM',
    espnAbbr: null,
    color: COLOR_MERCEDES,
    franchiseId: 'hamilton_lewis',
    subtitle: 'Mercedes',
  },
  {
    year: 2020,
    noChampion: false,
    name: 'Lewis Hamilton',
    abbr: 'HAM',
    espnAbbr: null,
    color: COLOR_MERCEDES,
    franchiseId: 'hamilton_lewis',
    subtitle: 'Mercedes',
  },
  {
    year: 2021,
    noChampion: false,
    name: 'Max Verstappen',
    abbr: 'VER',
    espnAbbr: null,
    color: COLOR_RED_BULL,
    franchiseId: 'verstappen_max',
    subtitle: 'Red Bull Racing-Honda',
  },
  {
    year: 2022,
    noChampion: false,
    name: 'Max Verstappen',
    abbr: 'VER',
    espnAbbr: null,
    color: COLOR_RED_BULL,
    franchiseId: 'verstappen_max',
    subtitle: 'Red Bull Racing',
  },
  {
    year: 2023,
    noChampion: false,
    name: 'Max Verstappen',
    abbr: 'VER',
    espnAbbr: null,
    color: COLOR_RED_BULL,
    franchiseId: 'verstappen_max',
    subtitle: 'Red Bull Racing',
  },
  {
    year: 2024,
    noChampion: false,
    name: 'Max Verstappen',
    abbr: 'VER',
    espnAbbr: null,
    color: COLOR_RED_BULL,
    franchiseId: 'verstappen_max',
    subtitle: 'Red Bull Racing',
  },
];
