// MLB World Series champion dataset.
// Continuous since 1903, with two exceptions:
//   - 1904: NL champion New York Giants refused to play the AL champion.
//   - 1994: players' strike cancelled the postseason.
// Both render as noChampion rows.
//
// Franchise continuity rules:
//   - Braves:    Boston -> Milwaukee -> Atlanta
//   - Dodgers:   Brooklyn -> Los Angeles
//   - Giants:    New York -> San Francisco
//   - Athletics: Philadelphia -> Kansas City -> Oakland
//   - Orioles:   St. Louis Browns -> Baltimore Orioles
//   - Twins:     (original) Washington Senators -> Minnesota Twins
//   - Rangers:   (expansion) Washington Senators -> Texas Rangers
//   - Nationals: Montreal Expos -> Washington Nationals
//
// Careful: Washington has had THREE separate franchises. The 1924
// Senators (champion) are the Twins lineage; the 1961-71 Senators are
// the Rangers lineage; the current Nationals are the Expos lineage.
// No title has been won under the Rangers-lineage Senators or the
// Expos name, so this file only surfaces the Twins-lineage 1924 Senators
// and the 2019 Washington Nationals. Both 2023 Rangers and 2019
// Nationals use their modern names/ids.
//
// Cleveland's franchise was renamed from "Indians" to "Guardians" in
// 2022. The two Cleveland titles (1920, 1948) are recorded under the
// era-appropriate name "Cleveland Indians" but share the modern
// `guardians` franchiseId so the rollup matches the current team.

import type { Row } from '../../shared/types';

export const CHAMPIONS: Row[] = [
  {
    year: 1903,
    noChampion: false,
    // The AL entry was the "Boston Americans"; the club was renamed
    // "Red Sox" in 1908 but shares the modern franchise id.
    name: 'Boston Americans',
    abbr: 'BOS',
    espnAbbr: 'bos',
    color: '#BD3039',
    franchiseId: 'red_sox',
  },
  {
    year: 1904,
    noChampion: true,
    reason: 'NL champion Giants refused to play',
  },
  {
    year: 1905,
    noChampion: false,
    name: 'New York Giants',
    abbr: 'NYG',
    espnAbbr: 'sf',
    color: '#FD5A1E',
    franchiseId: 'giants',
  },
  {
    year: 1906,
    noChampion: false,
    name: 'Chicago White Sox',
    abbr: 'CWS',
    espnAbbr: 'chw',
    color: '#27251F',
    franchiseId: 'white_sox',
  },
  {
    year: 1907,
    noChampion: false,
    name: 'Chicago Cubs',
    abbr: 'CHC',
    espnAbbr: 'chc',
    color: '#0E3386',
    franchiseId: 'cubs',
  },
  {
    year: 1908,
    noChampion: false,
    name: 'Chicago Cubs',
    abbr: 'CHC',
    espnAbbr: 'chc',
    color: '#0E3386',
    franchiseId: 'cubs',
  },
  {
    year: 1909,
    noChampion: false,
    name: 'Pittsburgh Pirates',
    abbr: 'PIT',
    espnAbbr: 'pit',
    color: '#FDB827',
    franchiseId: 'pirates',
  },
  {
    year: 1910,
    noChampion: false,
    name: 'Philadelphia Athletics',
    abbr: 'PHA',
    espnAbbr: 'oak',
    color: '#003831',
    franchiseId: 'athletics',
  },
  {
    year: 1911,
    noChampion: false,
    name: 'Philadelphia Athletics',
    abbr: 'PHA',
    espnAbbr: 'oak',
    color: '#003831',
    franchiseId: 'athletics',
  },
  {
    year: 1912,
    noChampion: false,
    name: 'Boston Red Sox',
    abbr: 'BOS',
    espnAbbr: 'bos',
    color: '#BD3039',
    franchiseId: 'red_sox',
  },
  {
    year: 1913,
    noChampion: false,
    name: 'Philadelphia Athletics',
    abbr: 'PHA',
    espnAbbr: 'oak',
    color: '#003831',
    franchiseId: 'athletics',
  },
  {
    year: 1914,
    noChampion: false,
    name: 'Boston Braves',
    abbr: 'BSN',
    espnAbbr: 'atl',
    color: '#13274F',
    franchiseId: 'braves',
  },
  {
    year: 1915,
    noChampion: false,
    name: 'Boston Red Sox',
    abbr: 'BOS',
    espnAbbr: 'bos',
    color: '#BD3039',
    franchiseId: 'red_sox',
  },
  {
    year: 1916,
    noChampion: false,
    name: 'Boston Red Sox',
    abbr: 'BOS',
    espnAbbr: 'bos',
    color: '#BD3039',
    franchiseId: 'red_sox',
  },
  {
    year: 1917,
    noChampion: false,
    name: 'Chicago White Sox',
    abbr: 'CWS',
    espnAbbr: 'chw',
    color: '#27251F',
    franchiseId: 'white_sox',
  },
  {
    year: 1918,
    noChampion: false,
    name: 'Boston Red Sox',
    abbr: 'BOS',
    espnAbbr: 'bos',
    color: '#BD3039',
    franchiseId: 'red_sox',
  },
  {
    year: 1919,
    noChampion: false,
    name: 'Cincinnati Reds',
    abbr: 'CIN',
    espnAbbr: 'cin',
    color: '#C6011F',
    franchiseId: 'reds',
  },
  {
    year: 1920,
    noChampion: false,
    // Franchise renamed "Guardians" in 2022; historical name retained
    // but franchiseId points at the modern club for rollup continuity.
    name: 'Cleveland Indians',
    abbr: 'CLE',
    espnAbbr: 'cle',
    color: '#00385D',
    franchiseId: 'guardians',
  },
  {
    year: 1921,
    noChampion: false,
    name: 'New York Giants',
    abbr: 'NYG',
    espnAbbr: 'sf',
    color: '#FD5A1E',
    franchiseId: 'giants',
  },
  {
    year: 1922,
    noChampion: false,
    name: 'New York Giants',
    abbr: 'NYG',
    espnAbbr: 'sf',
    color: '#FD5A1E',
    franchiseId: 'giants',
  },
  {
    year: 1923,
    noChampion: false,
    name: 'New York Yankees',
    abbr: 'NYY',
    espnAbbr: 'nyy',
    color: '#132448',
    franchiseId: 'yankees',
  },
  {
    year: 1924,
    noChampion: false,
    // ORIGINAL Washington Senators franchise -> became Minnesota Twins
    // in 1961. The second Senators franchise (1961-1971) became the
    // Texas Rangers. These are intentionally different franchiseIds.
    name: 'Washington Senators',
    abbr: 'WSH',
    espnAbbr: 'min',
    color: '#002B5C',
    franchiseId: 'twins',
  },
  {
    year: 1925,
    noChampion: false,
    name: 'Pittsburgh Pirates',
    abbr: 'PIT',
    espnAbbr: 'pit',
    color: '#FDB827',
    franchiseId: 'pirates',
  },
  {
    year: 1926,
    noChampion: false,
    name: 'St. Louis Cardinals',
    abbr: 'STL',
    espnAbbr: 'stl',
    color: '#C41E3A',
    franchiseId: 'cardinals',
  },
  {
    year: 1927,
    noChampion: false,
    name: 'New York Yankees',
    abbr: 'NYY',
    espnAbbr: 'nyy',
    color: '#132448',
    franchiseId: 'yankees',
  },
  {
    year: 1928,
    noChampion: false,
    name: 'New York Yankees',
    abbr: 'NYY',
    espnAbbr: 'nyy',
    color: '#132448',
    franchiseId: 'yankees',
  },
  {
    year: 1929,
    noChampion: false,
    name: 'Philadelphia Athletics',
    abbr: 'PHA',
    espnAbbr: 'oak',
    color: '#003831',
    franchiseId: 'athletics',
  },
  {
    year: 1930,
    noChampion: false,
    name: 'Philadelphia Athletics',
    abbr: 'PHA',
    espnAbbr: 'oak',
    color: '#003831',
    franchiseId: 'athletics',
  },
  {
    year: 1931,
    noChampion: false,
    name: 'St. Louis Cardinals',
    abbr: 'STL',
    espnAbbr: 'stl',
    color: '#C41E3A',
    franchiseId: 'cardinals',
  },
  {
    year: 1932,
    noChampion: false,
    name: 'New York Yankees',
    abbr: 'NYY',
    espnAbbr: 'nyy',
    color: '#132448',
    franchiseId: 'yankees',
  },
  {
    year: 1933,
    noChampion: false,
    name: 'New York Giants',
    abbr: 'NYG',
    espnAbbr: 'sf',
    color: '#FD5A1E',
    franchiseId: 'giants',
  },
  {
    year: 1934,
    noChampion: false,
    name: 'St. Louis Cardinals',
    abbr: 'STL',
    espnAbbr: 'stl',
    color: '#C41E3A',
    franchiseId: 'cardinals',
  },
  {
    year: 1935,
    noChampion: false,
    name: 'Detroit Tigers',
    abbr: 'DET',
    espnAbbr: 'det',
    color: '#0C2340',
    franchiseId: 'tigers',
  },
  {
    year: 1936,
    noChampion: false,
    name: 'New York Yankees',
    abbr: 'NYY',
    espnAbbr: 'nyy',
    color: '#132448',
    franchiseId: 'yankees',
  },
  {
    year: 1937,
    noChampion: false,
    name: 'New York Yankees',
    abbr: 'NYY',
    espnAbbr: 'nyy',
    color: '#132448',
    franchiseId: 'yankees',
  },
  {
    year: 1938,
    noChampion: false,
    name: 'New York Yankees',
    abbr: 'NYY',
    espnAbbr: 'nyy',
    color: '#132448',
    franchiseId: 'yankees',
  },
  {
    year: 1939,
    noChampion: false,
    name: 'New York Yankees',
    abbr: 'NYY',
    espnAbbr: 'nyy',
    color: '#132448',
    franchiseId: 'yankees',
  },
  {
    year: 1940,
    noChampion: false,
    name: 'Cincinnati Reds',
    abbr: 'CIN',
    espnAbbr: 'cin',
    color: '#C6011F',
    franchiseId: 'reds',
  },
  {
    year: 1941,
    noChampion: false,
    name: 'New York Yankees',
    abbr: 'NYY',
    espnAbbr: 'nyy',
    color: '#132448',
    franchiseId: 'yankees',
  },
  {
    year: 1942,
    noChampion: false,
    name: 'St. Louis Cardinals',
    abbr: 'STL',
    espnAbbr: 'stl',
    color: '#C41E3A',
    franchiseId: 'cardinals',
  },
  {
    year: 1943,
    noChampion: false,
    name: 'New York Yankees',
    abbr: 'NYY',
    espnAbbr: 'nyy',
    color: '#132448',
    franchiseId: 'yankees',
  },
  {
    year: 1944,
    noChampion: false,
    name: 'St. Louis Cardinals',
    abbr: 'STL',
    espnAbbr: 'stl',
    color: '#C41E3A',
    franchiseId: 'cardinals',
  },
  {
    year: 1945,
    noChampion: false,
    name: 'Detroit Tigers',
    abbr: 'DET',
    espnAbbr: 'det',
    color: '#0C2340',
    franchiseId: 'tigers',
  },
  {
    year: 1946,
    noChampion: false,
    name: 'St. Louis Cardinals',
    abbr: 'STL',
    espnAbbr: 'stl',
    color: '#C41E3A',
    franchiseId: 'cardinals',
  },
  {
    year: 1947,
    noChampion: false,
    name: 'New York Yankees',
    abbr: 'NYY',
    espnAbbr: 'nyy',
    color: '#132448',
    franchiseId: 'yankees',
  },
  {
    year: 1948,
    noChampion: false,
    name: 'Cleveland Indians',
    abbr: 'CLE',
    espnAbbr: 'cle',
    color: '#00385D',
    franchiseId: 'guardians',
  },
  {
    year: 1949,
    noChampion: false,
    name: 'New York Yankees',
    abbr: 'NYY',
    espnAbbr: 'nyy',
    color: '#132448',
    franchiseId: 'yankees',
  },
  {
    year: 1950,
    noChampion: false,
    name: 'New York Yankees',
    abbr: 'NYY',
    espnAbbr: 'nyy',
    color: '#132448',
    franchiseId: 'yankees',
  },
  {
    year: 1951,
    noChampion: false,
    name: 'New York Yankees',
    abbr: 'NYY',
    espnAbbr: 'nyy',
    color: '#132448',
    franchiseId: 'yankees',
  },
  {
    year: 1952,
    noChampion: false,
    name: 'New York Yankees',
    abbr: 'NYY',
    espnAbbr: 'nyy',
    color: '#132448',
    franchiseId: 'yankees',
  },
  {
    year: 1953,
    noChampion: false,
    name: 'New York Yankees',
    abbr: 'NYY',
    espnAbbr: 'nyy',
    color: '#132448',
    franchiseId: 'yankees',
  },
  {
    year: 1954,
    noChampion: false,
    name: 'New York Giants',
    abbr: 'NYG',
    espnAbbr: 'sf',
    color: '#FD5A1E',
    franchiseId: 'giants',
  },
  {
    year: 1955,
    noChampion: false,
    name: 'Brooklyn Dodgers',
    abbr: 'BKN',
    espnAbbr: 'lad',
    color: '#005A9C',
    franchiseId: 'dodgers',
  },
  {
    year: 1956,
    noChampion: false,
    name: 'New York Yankees',
    abbr: 'NYY',
    espnAbbr: 'nyy',
    color: '#132448',
    franchiseId: 'yankees',
  },
  {
    year: 1957,
    noChampion: false,
    name: 'Milwaukee Braves',
    abbr: 'MIL',
    espnAbbr: 'atl',
    color: '#13274F',
    franchiseId: 'braves',
  },
  {
    year: 1958,
    noChampion: false,
    name: 'New York Yankees',
    abbr: 'NYY',
    espnAbbr: 'nyy',
    color: '#132448',
    franchiseId: 'yankees',
  },
  {
    year: 1959,
    noChampion: false,
    name: 'Los Angeles Dodgers',
    abbr: 'LAD',
    espnAbbr: 'lad',
    color: '#005A9C',
    franchiseId: 'dodgers',
  },
  {
    year: 1960,
    noChampion: false,
    name: 'Pittsburgh Pirates',
    abbr: 'PIT',
    espnAbbr: 'pit',
    color: '#FDB827',
    franchiseId: 'pirates',
  },
  {
    year: 1961,
    noChampion: false,
    name: 'New York Yankees',
    abbr: 'NYY',
    espnAbbr: 'nyy',
    color: '#132448',
    franchiseId: 'yankees',
  },
  {
    year: 1962,
    noChampion: false,
    name: 'New York Yankees',
    abbr: 'NYY',
    espnAbbr: 'nyy',
    color: '#132448',
    franchiseId: 'yankees',
  },
  {
    year: 1963,
    noChampion: false,
    name: 'Los Angeles Dodgers',
    abbr: 'LAD',
    espnAbbr: 'lad',
    color: '#005A9C',
    franchiseId: 'dodgers',
  },
  {
    year: 1964,
    noChampion: false,
    name: 'St. Louis Cardinals',
    abbr: 'STL',
    espnAbbr: 'stl',
    color: '#C41E3A',
    franchiseId: 'cardinals',
  },
  {
    year: 1965,
    noChampion: false,
    name: 'Los Angeles Dodgers',
    abbr: 'LAD',
    espnAbbr: 'lad',
    color: '#005A9C',
    franchiseId: 'dodgers',
  },
  {
    year: 1966,
    noChampion: false,
    name: 'Baltimore Orioles',
    abbr: 'BAL',
    espnAbbr: 'bal',
    color: '#DF4601',
    franchiseId: 'orioles',
  },
  {
    year: 1967,
    noChampion: false,
    name: 'St. Louis Cardinals',
    abbr: 'STL',
    espnAbbr: 'stl',
    color: '#C41E3A',
    franchiseId: 'cardinals',
  },
  {
    year: 1968,
    noChampion: false,
    name: 'Detroit Tigers',
    abbr: 'DET',
    espnAbbr: 'det',
    color: '#0C2340',
    franchiseId: 'tigers',
  },
  {
    year: 1969,
    noChampion: false,
    name: 'New York Mets',
    abbr: 'NYM',
    espnAbbr: 'nym',
    color: '#002D72',
    franchiseId: 'mets',
  },
  {
    year: 1970,
    noChampion: false,
    name: 'Baltimore Orioles',
    abbr: 'BAL',
    espnAbbr: 'bal',
    color: '#DF4601',
    franchiseId: 'orioles',
  },
  {
    year: 1971,
    noChampion: false,
    name: 'Pittsburgh Pirates',
    abbr: 'PIT',
    espnAbbr: 'pit',
    color: '#FDB827',
    franchiseId: 'pirates',
  },
  {
    year: 1972,
    noChampion: false,
    name: 'Oakland Athletics',
    abbr: 'OAK',
    espnAbbr: 'oak',
    color: '#003831',
    franchiseId: 'athletics',
  },
  {
    year: 1973,
    noChampion: false,
    name: 'Oakland Athletics',
    abbr: 'OAK',
    espnAbbr: 'oak',
    color: '#003831',
    franchiseId: 'athletics',
  },
  {
    year: 1974,
    noChampion: false,
    name: 'Oakland Athletics',
    abbr: 'OAK',
    espnAbbr: 'oak',
    color: '#003831',
    franchiseId: 'athletics',
  },
  {
    year: 1975,
    noChampion: false,
    name: 'Cincinnati Reds',
    abbr: 'CIN',
    espnAbbr: 'cin',
    color: '#C6011F',
    franchiseId: 'reds',
  },
  {
    year: 1976,
    noChampion: false,
    name: 'Cincinnati Reds',
    abbr: 'CIN',
    espnAbbr: 'cin',
    color: '#C6011F',
    franchiseId: 'reds',
  },
  {
    year: 1977,
    noChampion: false,
    name: 'New York Yankees',
    abbr: 'NYY',
    espnAbbr: 'nyy',
    color: '#132448',
    franchiseId: 'yankees',
  },
  {
    year: 1978,
    noChampion: false,
    name: 'New York Yankees',
    abbr: 'NYY',
    espnAbbr: 'nyy',
    color: '#132448',
    franchiseId: 'yankees',
  },
  {
    year: 1979,
    noChampion: false,
    name: 'Pittsburgh Pirates',
    abbr: 'PIT',
    espnAbbr: 'pit',
    color: '#FDB827',
    franchiseId: 'pirates',
  },
  {
    year: 1980,
    noChampion: false,
    name: 'Philadelphia Phillies',
    abbr: 'PHI',
    espnAbbr: 'phi',
    color: '#E81828',
    franchiseId: 'phillies',
  },
  {
    year: 1981,
    noChampion: false,
    name: 'Los Angeles Dodgers',
    abbr: 'LAD',
    espnAbbr: 'lad',
    color: '#005A9C',
    franchiseId: 'dodgers',
  },
  {
    year: 1982,
    noChampion: false,
    name: 'St. Louis Cardinals',
    abbr: 'STL',
    espnAbbr: 'stl',
    color: '#C41E3A',
    franchiseId: 'cardinals',
  },
  {
    year: 1983,
    noChampion: false,
    name: 'Baltimore Orioles',
    abbr: 'BAL',
    espnAbbr: 'bal',
    color: '#DF4601',
    franchiseId: 'orioles',
  },
  {
    year: 1984,
    noChampion: false,
    name: 'Detroit Tigers',
    abbr: 'DET',
    espnAbbr: 'det',
    color: '#0C2340',
    franchiseId: 'tigers',
  },
  {
    year: 1985,
    noChampion: false,
    name: 'Kansas City Royals',
    abbr: 'KC',
    espnAbbr: 'kc',
    color: '#004687',
    franchiseId: 'royals',
  },
  {
    year: 1986,
    noChampion: false,
    name: 'New York Mets',
    abbr: 'NYM',
    espnAbbr: 'nym',
    color: '#002D72',
    franchiseId: 'mets',
  },
  {
    year: 1987,
    noChampion: false,
    name: 'Minnesota Twins',
    abbr: 'MIN',
    espnAbbr: 'min',
    color: '#002B5C',
    franchiseId: 'twins',
  },
  {
    year: 1988,
    noChampion: false,
    name: 'Los Angeles Dodgers',
    abbr: 'LAD',
    espnAbbr: 'lad',
    color: '#005A9C',
    franchiseId: 'dodgers',
  },
  {
    year: 1989,
    noChampion: false,
    name: 'Oakland Athletics',
    abbr: 'OAK',
    espnAbbr: 'oak',
    color: '#003831',
    franchiseId: 'athletics',
  },
  {
    year: 1990,
    noChampion: false,
    name: 'Cincinnati Reds',
    abbr: 'CIN',
    espnAbbr: 'cin',
    color: '#C6011F',
    franchiseId: 'reds',
  },
  {
    year: 1991,
    noChampion: false,
    name: 'Minnesota Twins',
    abbr: 'MIN',
    espnAbbr: 'min',
    color: '#002B5C',
    franchiseId: 'twins',
  },
  {
    year: 1992,
    noChampion: false,
    name: 'Toronto Blue Jays',
    abbr: 'TOR',
    espnAbbr: 'tor',
    color: '#134A8E',
    franchiseId: 'blue_jays',
  },
  {
    year: 1993,
    noChampion: false,
    name: 'Toronto Blue Jays',
    abbr: 'TOR',
    espnAbbr: 'tor',
    color: '#134A8E',
    franchiseId: 'blue_jays',
  },
  {
    year: 1994,
    noChampion: true,
    reason: 'players\u2019 strike',
  },
  {
    year: 1995,
    noChampion: false,
    name: 'Atlanta Braves',
    abbr: 'ATL',
    espnAbbr: 'atl',
    color: '#13274F',
    franchiseId: 'braves',
  },
  {
    year: 1996,
    noChampion: false,
    name: 'New York Yankees',
    abbr: 'NYY',
    espnAbbr: 'nyy',
    color: '#132448',
    franchiseId: 'yankees',
  },
  {
    year: 1997,
    noChampion: false,
    // Franchise was the "Florida Marlins" until 2012; renamed "Miami
    // Marlins" that offseason. Both eras roll up under `marlins`.
    name: 'Florida Marlins',
    abbr: 'FLA',
    espnAbbr: 'mia',
    color: '#00A3E0',
    franchiseId: 'marlins',
  },
  {
    year: 1998,
    noChampion: false,
    name: 'New York Yankees',
    abbr: 'NYY',
    espnAbbr: 'nyy',
    color: '#132448',
    franchiseId: 'yankees',
  },
  {
    year: 1999,
    noChampion: false,
    name: 'New York Yankees',
    abbr: 'NYY',
    espnAbbr: 'nyy',
    color: '#132448',
    franchiseId: 'yankees',
  },
  {
    year: 2000,
    noChampion: false,
    name: 'New York Yankees',
    abbr: 'NYY',
    espnAbbr: 'nyy',
    color: '#132448',
    franchiseId: 'yankees',
  },
  {
    year: 2001,
    noChampion: false,
    name: 'Arizona Diamondbacks',
    abbr: 'ARI',
    espnAbbr: 'ari',
    color: '#A71930',
    franchiseId: 'diamondbacks',
  },
  {
    year: 2002,
    noChampion: false,
    // Marketed as the "Anaheim Angels" in 2002; same franchise as the
    // current Los Angeles Angels. Uses the stable `angels` id.
    name: 'Anaheim Angels',
    abbr: 'ANA',
    espnAbbr: 'laa',
    color: '#BA0021',
    franchiseId: 'angels',
  },
  {
    year: 2003,
    noChampion: false,
    name: 'Florida Marlins',
    abbr: 'FLA',
    espnAbbr: 'mia',
    color: '#00A3E0',
    franchiseId: 'marlins',
  },
  {
    year: 2004,
    noChampion: false,
    name: 'Boston Red Sox',
    abbr: 'BOS',
    espnAbbr: 'bos',
    color: '#BD3039',
    franchiseId: 'red_sox',
  },
  {
    year: 2005,
    noChampion: false,
    name: 'Chicago White Sox',
    abbr: 'CWS',
    espnAbbr: 'chw',
    color: '#27251F',
    franchiseId: 'white_sox',
  },
  {
    year: 2006,
    noChampion: false,
    name: 'St. Louis Cardinals',
    abbr: 'STL',
    espnAbbr: 'stl',
    color: '#C41E3A',
    franchiseId: 'cardinals',
  },
  {
    year: 2007,
    noChampion: false,
    name: 'Boston Red Sox',
    abbr: 'BOS',
    espnAbbr: 'bos',
    color: '#BD3039',
    franchiseId: 'red_sox',
  },
  {
    year: 2008,
    noChampion: false,
    name: 'Philadelphia Phillies',
    abbr: 'PHI',
    espnAbbr: 'phi',
    color: '#E81828',
    franchiseId: 'phillies',
  },
  {
    year: 2009,
    noChampion: false,
    name: 'New York Yankees',
    abbr: 'NYY',
    espnAbbr: 'nyy',
    color: '#132448',
    franchiseId: 'yankees',
  },
  {
    year: 2010,
    noChampion: false,
    name: 'San Francisco Giants',
    abbr: 'SF',
    espnAbbr: 'sf',
    color: '#FD5A1E',
    franchiseId: 'giants',
  },
  {
    year: 2011,
    noChampion: false,
    name: 'St. Louis Cardinals',
    abbr: 'STL',
    espnAbbr: 'stl',
    color: '#C41E3A',
    franchiseId: 'cardinals',
  },
  {
    year: 2012,
    noChampion: false,
    name: 'San Francisco Giants',
    abbr: 'SF',
    espnAbbr: 'sf',
    color: '#FD5A1E',
    franchiseId: 'giants',
  },
  {
    year: 2013,
    noChampion: false,
    name: 'Boston Red Sox',
    abbr: 'BOS',
    espnAbbr: 'bos',
    color: '#BD3039',
    franchiseId: 'red_sox',
  },
  {
    year: 2014,
    noChampion: false,
    name: 'San Francisco Giants',
    abbr: 'SF',
    espnAbbr: 'sf',
    color: '#FD5A1E',
    franchiseId: 'giants',
  },
  {
    year: 2015,
    noChampion: false,
    name: 'Kansas City Royals',
    abbr: 'KC',
    espnAbbr: 'kc',
    color: '#004687',
    franchiseId: 'royals',
  },
  {
    year: 2016,
    noChampion: false,
    name: 'Chicago Cubs',
    abbr: 'CHC',
    espnAbbr: 'chc',
    color: '#0E3386',
    franchiseId: 'cubs',
  },
  {
    year: 2017,
    noChampion: false,
    name: 'Houston Astros',
    abbr: 'HOU',
    espnAbbr: 'hou',
    color: '#EB6E1F',
    franchiseId: 'astros',
  },
  {
    year: 2018,
    noChampion: false,
    name: 'Boston Red Sox',
    abbr: 'BOS',
    espnAbbr: 'bos',
    color: '#BD3039',
    franchiseId: 'red_sox',
  },
  {
    year: 2019,
    noChampion: false,
    name: 'Washington Nationals',
    abbr: 'WSH',
    espnAbbr: 'wsh',
    color: '#AB0003',
    franchiseId: 'nationals',
  },
  {
    year: 2020,
    noChampion: false,
    name: 'Los Angeles Dodgers',
    abbr: 'LAD',
    espnAbbr: 'lad',
    color: '#005A9C',
    franchiseId: 'dodgers',
  },
  {
    year: 2021,
    noChampion: false,
    name: 'Atlanta Braves',
    abbr: 'ATL',
    espnAbbr: 'atl',
    color: '#13274F',
    franchiseId: 'braves',
  },
  {
    year: 2022,
    noChampion: false,
    name: 'Houston Astros',
    abbr: 'HOU',
    espnAbbr: 'hou',
    color: '#EB6E1F',
    franchiseId: 'astros',
  },
  {
    year: 2023,
    noChampion: false,
    name: 'Texas Rangers',
    abbr: 'TEX',
    espnAbbr: 'tex',
    color: '#003278',
    franchiseId: 'rangers',
  },
  {
    year: 2024,
    noChampion: false,
    name: 'Los Angeles Dodgers',
    abbr: 'LAD',
    espnAbbr: 'lad',
    color: '#005A9C',
    franchiseId: 'dodgers',
  },
  {
    year: 2025,
    noChampion: false,
    name: 'Los Angeles Dodgers',
    abbr: 'LAD',
    espnAbbr: 'lad',
    color: '#005A9C',
    franchiseId: 'dodgers',
  },
];
