// NFL Super Bowl champion dataset.
// Each row's `year` is the SEASON YEAR (NFL convention) — Super Bowl I
// was the 1966 season, played Jan 1967. The Super Bowl is the only
// championship counted here, per the spec (pre-1966 NFL Championship era
// is out of scope).
//
// Franchise continuity rules (follow NFL's own rulings):
//   - Raiders: Oakland → LA → Oakland → Las Vegas = one franchise (`raiders`).
//   - Rams: LA → St. Louis → LA = one franchise (`rams`).
//   - Colts: Baltimore → Indianapolis = one franchise (`colts`).
//   - Commanders: Redskins → Washington Football Team → Commanders
//     = one franchise (`commanders`).
//   - Ravens / Browns: distinct franchises. Ravens are treated as a
//     1996-founded expansion; pre-1996 Cleveland records stay with the
//     Browns franchise (which has never won a Super Bowl and therefore
//     doesn't appear in this file).

import type { Row } from '../../shared/types';

export const CHAMPIONS: Row[] = [
  {
    year: 1966,
    noChampion: false,
    name: 'Green Bay Packers',
    abbr: 'GB',
    espnAbbr: 'gb',
    color: '#203731',
    franchiseId: 'packers',
  },
  {
    year: 1967,
    noChampion: false,
    name: 'Green Bay Packers',
    abbr: 'GB',
    espnAbbr: 'gb',
    color: '#203731',
    franchiseId: 'packers',
  },
  {
    year: 1968,
    noChampion: false,
    name: 'New York Jets',
    abbr: 'NYJ',
    espnAbbr: 'nyj',
    color: '#125740',
    franchiseId: 'jets',
  },
  {
    year: 1969,
    noChampion: false,
    name: 'Kansas City Chiefs',
    abbr: 'KC',
    espnAbbr: 'kc',
    color: '#E31837',
    franchiseId: 'chiefs',
  },
  {
    year: 1970,
    noChampion: false,
    name: 'Baltimore Colts',
    abbr: 'BAL',
    espnAbbr: 'ind',
    color: '#002C5F',
    franchiseId: 'colts',
  },
  {
    year: 1971,
    noChampion: false,
    name: 'Dallas Cowboys',
    abbr: 'DAL',
    espnAbbr: 'dal',
    color: '#003594',
    franchiseId: 'cowboys',
  },
  {
    year: 1972,
    noChampion: false,
    name: 'Miami Dolphins',
    abbr: 'MIA',
    espnAbbr: 'mia',
    color: '#008E97',
    franchiseId: 'dolphins',
  },
  {
    year: 1973,
    noChampion: false,
    name: 'Miami Dolphins',
    abbr: 'MIA',
    espnAbbr: 'mia',
    color: '#008E97',
    franchiseId: 'dolphins',
  },
  {
    year: 1974,
    noChampion: false,
    name: 'Pittsburgh Steelers',
    abbr: 'PIT',
    espnAbbr: 'pit',
    color: '#101820',
    franchiseId: 'steelers',
  },
  {
    year: 1975,
    noChampion: false,
    name: 'Pittsburgh Steelers',
    abbr: 'PIT',
    espnAbbr: 'pit',
    color: '#101820',
    franchiseId: 'steelers',
  },
  {
    year: 1976,
    noChampion: false,
    name: 'Oakland Raiders',
    abbr: 'OAK',
    espnAbbr: 'lv',
    color: '#000000',
    franchiseId: 'raiders',
  },
  {
    year: 1977,
    noChampion: false,
    name: 'Dallas Cowboys',
    abbr: 'DAL',
    espnAbbr: 'dal',
    color: '#003594',
    franchiseId: 'cowboys',
  },
  {
    year: 1978,
    noChampion: false,
    name: 'Pittsburgh Steelers',
    abbr: 'PIT',
    espnAbbr: 'pit',
    color: '#101820',
    franchiseId: 'steelers',
  },
  {
    year: 1979,
    noChampion: false,
    name: 'Pittsburgh Steelers',
    abbr: 'PIT',
    espnAbbr: 'pit',
    color: '#101820',
    franchiseId: 'steelers',
  },
  {
    year: 1980,
    noChampion: false,
    name: 'Oakland Raiders',
    abbr: 'OAK',
    espnAbbr: 'lv',
    color: '#000000',
    franchiseId: 'raiders',
  },
  {
    year: 1981,
    noChampion: false,
    name: 'San Francisco 49ers',
    abbr: 'SF',
    espnAbbr: 'sf',
    color: '#AA0000',
    franchiseId: '49ers',
  },
  {
    year: 1982,
    noChampion: false,
    name: 'Washington Redskins',
    abbr: 'WAS',
    espnAbbr: 'wsh',
    color: '#5A1414',
    franchiseId: 'commanders',
  },
  {
    year: 1983,
    noChampion: false,
    name: 'Los Angeles Raiders',
    abbr: 'LAR',
    espnAbbr: 'lv',
    color: '#000000',
    franchiseId: 'raiders',
  },
  {
    year: 1984,
    noChampion: false,
    name: 'San Francisco 49ers',
    abbr: 'SF',
    espnAbbr: 'sf',
    color: '#AA0000',
    franchiseId: '49ers',
  },
  {
    year: 1985,
    noChampion: false,
    name: 'Chicago Bears',
    abbr: 'CHI',
    espnAbbr: 'chi',
    color: '#0B162A',
    franchiseId: 'bears',
  },
  {
    year: 1986,
    noChampion: false,
    name: 'New York Giants',
    abbr: 'NYG',
    espnAbbr: 'nyg',
    color: '#0B2265',
    franchiseId: 'giants',
  },
  {
    year: 1987,
    noChampion: false,
    name: 'Washington Redskins',
    abbr: 'WAS',
    espnAbbr: 'wsh',
    color: '#5A1414',
    franchiseId: 'commanders',
  },
  {
    year: 1988,
    noChampion: false,
    name: 'San Francisco 49ers',
    abbr: 'SF',
    espnAbbr: 'sf',
    color: '#AA0000',
    franchiseId: '49ers',
  },
  {
    year: 1989,
    noChampion: false,
    name: 'San Francisco 49ers',
    abbr: 'SF',
    espnAbbr: 'sf',
    color: '#AA0000',
    franchiseId: '49ers',
  },
  {
    year: 1990,
    noChampion: false,
    name: 'New York Giants',
    abbr: 'NYG',
    espnAbbr: 'nyg',
    color: '#0B2265',
    franchiseId: 'giants',
  },
  {
    year: 1991,
    noChampion: false,
    name: 'Washington Redskins',
    abbr: 'WAS',
    espnAbbr: 'wsh',
    color: '#5A1414',
    franchiseId: 'commanders',
  },
  {
    year: 1992,
    noChampion: false,
    name: 'Dallas Cowboys',
    abbr: 'DAL',
    espnAbbr: 'dal',
    color: '#003594',
    franchiseId: 'cowboys',
  },
  {
    year: 1993,
    noChampion: false,
    name: 'Dallas Cowboys',
    abbr: 'DAL',
    espnAbbr: 'dal',
    color: '#003594',
    franchiseId: 'cowboys',
  },
  {
    year: 1994,
    noChampion: false,
    name: 'San Francisco 49ers',
    abbr: 'SF',
    espnAbbr: 'sf',
    color: '#AA0000',
    franchiseId: '49ers',
  },
  {
    year: 1995,
    noChampion: false,
    name: 'Dallas Cowboys',
    abbr: 'DAL',
    espnAbbr: 'dal',
    color: '#003594',
    franchiseId: 'cowboys',
  },
  {
    year: 1996,
    noChampion: false,
    name: 'Green Bay Packers',
    abbr: 'GB',
    espnAbbr: 'gb',
    color: '#203731',
    franchiseId: 'packers',
  },
  {
    year: 1997,
    noChampion: false,
    name: 'Denver Broncos',
    abbr: 'DEN',
    espnAbbr: 'den',
    color: '#FB4F14',
    franchiseId: 'broncos',
  },
  {
    year: 1998,
    noChampion: false,
    name: 'Denver Broncos',
    abbr: 'DEN',
    espnAbbr: 'den',
    color: '#FB4F14',
    franchiseId: 'broncos',
  },
  {
    year: 1999,
    noChampion: false,
    name: 'St. Louis Rams',
    abbr: 'STL',
    espnAbbr: 'lar',
    color: '#003594',
    franchiseId: 'rams',
  },
  {
    year: 2000,
    noChampion: false,
    name: 'Baltimore Ravens',
    abbr: 'BAL',
    espnAbbr: 'bal',
    color: '#241773',
    franchiseId: 'ravens',
  },
  {
    year: 2001,
    noChampion: false,
    name: 'New England Patriots',
    abbr: 'NE',
    espnAbbr: 'ne',
    color: '#002244',
    franchiseId: 'patriots',
  },
  {
    year: 2002,
    noChampion: false,
    name: 'Tampa Bay Buccaneers',
    abbr: 'TB',
    espnAbbr: 'tb',
    color: '#D50A0A',
    franchiseId: 'buccaneers',
  },
  {
    year: 2003,
    noChampion: false,
    name: 'New England Patriots',
    abbr: 'NE',
    espnAbbr: 'ne',
    color: '#002244',
    franchiseId: 'patriots',
  },
  {
    year: 2004,
    noChampion: false,
    name: 'New England Patriots',
    abbr: 'NE',
    espnAbbr: 'ne',
    color: '#002244',
    franchiseId: 'patriots',
  },
  {
    year: 2005,
    noChampion: false,
    name: 'Pittsburgh Steelers',
    abbr: 'PIT',
    espnAbbr: 'pit',
    color: '#101820',
    franchiseId: 'steelers',
  },
  {
    year: 2006,
    noChampion: false,
    name: 'Indianapolis Colts',
    abbr: 'IND',
    espnAbbr: 'ind',
    color: '#002C5F',
    franchiseId: 'colts',
  },
  {
    year: 2007,
    noChampion: false,
    name: 'New York Giants',
    abbr: 'NYG',
    espnAbbr: 'nyg',
    color: '#0B2265',
    franchiseId: 'giants',
  },
  {
    year: 2008,
    noChampion: false,
    name: 'Pittsburgh Steelers',
    abbr: 'PIT',
    espnAbbr: 'pit',
    color: '#101820',
    franchiseId: 'steelers',
  },
  {
    year: 2009,
    noChampion: false,
    name: 'New Orleans Saints',
    abbr: 'NO',
    espnAbbr: 'no',
    color: '#101820',
    franchiseId: 'saints',
  },
  {
    year: 2010,
    noChampion: false,
    name: 'Green Bay Packers',
    abbr: 'GB',
    espnAbbr: 'gb',
    color: '#203731',
    franchiseId: 'packers',
  },
  {
    year: 2011,
    noChampion: false,
    name: 'New York Giants',
    abbr: 'NYG',
    espnAbbr: 'nyg',
    color: '#0B2265',
    franchiseId: 'giants',
  },
  {
    year: 2012,
    noChampion: false,
    name: 'Baltimore Ravens',
    abbr: 'BAL',
    espnAbbr: 'bal',
    color: '#241773',
    franchiseId: 'ravens',
  },
  {
    year: 2013,
    noChampion: false,
    name: 'Seattle Seahawks',
    abbr: 'SEA',
    espnAbbr: 'sea',
    color: '#002244',
    franchiseId: 'seahawks',
  },
  {
    year: 2014,
    noChampion: false,
    name: 'New England Patriots',
    abbr: 'NE',
    espnAbbr: 'ne',
    color: '#002244',
    franchiseId: 'patriots',
  },
  {
    year: 2015,
    noChampion: false,
    name: 'Denver Broncos',
    abbr: 'DEN',
    espnAbbr: 'den',
    color: '#FB4F14',
    franchiseId: 'broncos',
  },
  {
    year: 2016,
    noChampion: false,
    name: 'New England Patriots',
    abbr: 'NE',
    espnAbbr: 'ne',
    color: '#002244',
    franchiseId: 'patriots',
  },
  {
    year: 2017,
    noChampion: false,
    name: 'Philadelphia Eagles',
    abbr: 'PHI',
    espnAbbr: 'phi',
    color: '#004C54',
    franchiseId: 'eagles',
  },
  {
    year: 2018,
    noChampion: false,
    name: 'New England Patriots',
    abbr: 'NE',
    espnAbbr: 'ne',
    color: '#002244',
    franchiseId: 'patriots',
  },
  {
    year: 2019,
    noChampion: false,
    name: 'Kansas City Chiefs',
    abbr: 'KC',
    espnAbbr: 'kc',
    color: '#E31837',
    franchiseId: 'chiefs',
  },
  {
    year: 2020,
    noChampion: false,
    name: 'Tampa Bay Buccaneers',
    abbr: 'TB',
    espnAbbr: 'tb',
    color: '#D50A0A',
    franchiseId: 'buccaneers',
  },
  {
    year: 2021,
    noChampion: false,
    name: 'Los Angeles Rams',
    abbr: 'LAR',
    espnAbbr: 'lar',
    color: '#003594',
    franchiseId: 'rams',
  },
  {
    year: 2022,
    noChampion: false,
    name: 'Kansas City Chiefs',
    abbr: 'KC',
    espnAbbr: 'kc',
    color: '#E31837',
    franchiseId: 'chiefs',
  },
  {
    year: 2023,
    noChampion: false,
    name: 'Kansas City Chiefs',
    abbr: 'KC',
    espnAbbr: 'kc',
    color: '#E31837',
    franchiseId: 'chiefs',
  },
  {
    year: 2024,
    noChampion: false,
    name: 'Philadelphia Eagles',
    abbr: 'PHI',
    espnAbbr: 'phi',
    color: '#004C54',
    franchiseId: 'eagles',
  },
];
