// Stanley Cup champion dataset.
// Each champion carries the franchise_id used to compute running cup totals
// across name changes (e.g. Toronto Blueshirts → Arenas → St. Patricks → Maple Leafs
// all share `toronto`; Ottawa Silver Seven → original Ottawa Senators share `ottawa_og`).
// The modern Ottawa Senators (1992–) are a separate franchise and are not in this list.
export type Champion =
  | {
      year: number;
      noChampion: false;
      name: string;
      abbr: string;
      espnAbbr: string | null;
      color: string;
      franchiseId: string;
    }
  | {
      year: number;
      noChampion: true;
      reason: string;
    };

export const CHAMPIONS: Champion[] = [
  // Challenge Era (1893–1913)
  {
    year: 1893,
    noChampion: false,
    name: 'Montreal HC',
    abbr: 'MHC',
    espnAbbr: null,
    color: '#1a3a5c',
    franchiseId: 'montreal_hc',
  },
  {
    year: 1894,
    noChampion: false,
    name: 'Montreal HC',
    abbr: 'MHC',
    espnAbbr: null,
    color: '#1a3a5c',
    franchiseId: 'montreal_hc',
  },
  {
    year: 1895,
    noChampion: false,
    name: 'Montreal Victorias',
    abbr: 'MVIC',
    espnAbbr: null,
    color: '#6b1d3a',
    franchiseId: 'montreal_vic',
  },
  {
    year: 1896,
    noChampion: false,
    name: 'Montreal Victorias',
    abbr: 'MVIC',
    espnAbbr: null,
    color: '#6b1d3a',
    franchiseId: 'montreal_vic',
  },
  {
    year: 1897,
    noChampion: false,
    name: 'Montreal Victorias',
    abbr: 'MVIC',
    espnAbbr: null,
    color: '#6b1d3a',
    franchiseId: 'montreal_vic',
  },
  {
    year: 1898,
    noChampion: false,
    name: 'Montreal Victorias',
    abbr: 'MVIC',
    espnAbbr: null,
    color: '#6b1d3a',
    franchiseId: 'montreal_vic',
  },
  {
    year: 1899,
    noChampion: false,
    name: 'Montreal Shamrocks',
    abbr: 'MSHM',
    espnAbbr: null,
    color: '#1a6b3a',
    franchiseId: 'montreal_sh',
  },
  {
    year: 1900,
    noChampion: false,
    name: 'Montreal Shamrocks',
    abbr: 'MSHM',
    espnAbbr: null,
    color: '#1a6b3a',
    franchiseId: 'montreal_sh',
  },
  {
    year: 1901,
    noChampion: false,
    name: 'Winnipeg Victorias',
    abbr: 'WVIC',
    espnAbbr: null,
    color: '#2a4a6a',
    franchiseId: 'winnipeg_vic',
  },
  {
    year: 1902,
    noChampion: false,
    name: 'Montreal HC',
    abbr: 'MHC',
    espnAbbr: null,
    color: '#1a3a5c',
    franchiseId: 'montreal_hc',
  },
  {
    year: 1903,
    noChampion: false,
    name: 'Ottawa Silver Seven',
    abbr: 'OTT',
    espnAbbr: null,
    color: '#c42b34',
    franchiseId: 'ottawa_og',
  },
  {
    year: 1904,
    noChampion: false,
    name: 'Ottawa Silver Seven',
    abbr: 'OTT',
    espnAbbr: null,
    color: '#c42b34',
    franchiseId: 'ottawa_og',
  },
  {
    year: 1905,
    noChampion: false,
    name: 'Ottawa Silver Seven',
    abbr: 'OTT',
    espnAbbr: null,
    color: '#c42b34',
    franchiseId: 'ottawa_og',
  },
  {
    year: 1906,
    noChampion: false,
    name: 'Montreal Wanderers',
    abbr: 'MWAN',
    espnAbbr: null,
    color: '#cc2244',
    franchiseId: 'montreal_wan',
  },
  {
    year: 1907,
    noChampion: false,
    name: 'Montreal Wanderers',
    abbr: 'MWAN',
    espnAbbr: null,
    color: '#cc2244',
    franchiseId: 'montreal_wan',
  },
  {
    year: 1908,
    noChampion: false,
    name: 'Montreal Wanderers',
    abbr: 'MWAN',
    espnAbbr: null,
    color: '#cc2244',
    franchiseId: 'montreal_wan',
  },
  {
    year: 1909,
    noChampion: false,
    name: 'Ottawa Senators',
    abbr: 'OTT',
    espnAbbr: null,
    color: '#c42b34',
    franchiseId: 'ottawa_og',
  },
  {
    year: 1910,
    noChampion: false,
    name: 'Montreal Wanderers',
    abbr: 'MWAN',
    espnAbbr: null,
    color: '#cc2244',
    franchiseId: 'montreal_wan',
  },
  {
    year: 1911,
    noChampion: false,
    name: 'Ottawa Senators',
    abbr: 'OTT',
    espnAbbr: null,
    color: '#c42b34',
    franchiseId: 'ottawa_og',
  },
  {
    year: 1912,
    noChampion: false,
    name: 'Quebec Bulldogs',
    abbr: 'QUE',
    espnAbbr: null,
    color: '#2244aa',
    franchiseId: 'quebec',
  },
  {
    year: 1913,
    noChampion: false,
    name: 'Quebec Bulldogs',
    abbr: 'QUE',
    espnAbbr: null,
    color: '#2244aa',
    franchiseId: 'quebec',
  },

  // Interleague Era (1914–1926)
  {
    year: 1914,
    noChampion: false,
    name: 'Toronto Blueshirts',
    abbr: 'TOR',
    espnAbbr: null,
    color: '#00539B',
    franchiseId: 'toronto',
  },
  {
    year: 1915,
    noChampion: false,
    name: 'Vancouver Millionaires',
    abbr: 'VAN',
    espnAbbr: null,
    color: '#5c1a2a',
    franchiseId: 'vancouver',
  },
  {
    year: 1916,
    noChampion: false,
    name: 'Montreal Canadiens',
    abbr: 'MTL',
    espnAbbr: 'mtl',
    color: '#AF1E2D',
    franchiseId: 'canadiens',
  },
  {
    year: 1917,
    noChampion: false,
    name: 'Seattle Metropolitans',
    abbr: 'SEA',
    espnAbbr: null,
    color: '#cc3333',
    franchiseId: 'seattle',
  },
  {
    year: 1918,
    noChampion: false,
    name: 'Toronto Arenas',
    abbr: 'TOR',
    espnAbbr: null,
    color: '#00539B',
    franchiseId: 'toronto',
  },
  { year: 1919, noChampion: true, reason: 'influenza' },
  {
    year: 1920,
    noChampion: false,
    name: 'Ottawa Senators',
    abbr: 'OTT',
    espnAbbr: null,
    color: '#c42b34',
    franchiseId: 'ottawa_og',
  },
  {
    year: 1921,
    noChampion: false,
    name: 'Ottawa Senators',
    abbr: 'OTT',
    espnAbbr: null,
    color: '#c42b34',
    franchiseId: 'ottawa_og',
  },
  {
    year: 1922,
    noChampion: false,
    name: 'Toronto St. Patricks',
    abbr: 'TOR',
    espnAbbr: null,
    color: '#00843D',
    franchiseId: 'toronto',
  },
  {
    year: 1923,
    noChampion: false,
    name: 'Ottawa Senators',
    abbr: 'OTT',
    espnAbbr: null,
    color: '#c42b34',
    franchiseId: 'ottawa_og',
  },
  {
    year: 1924,
    noChampion: false,
    name: 'Montreal Canadiens',
    abbr: 'MTL',
    espnAbbr: 'mtl',
    color: '#AF1E2D',
    franchiseId: 'canadiens',
  },
  {
    year: 1925,
    noChampion: false,
    name: 'Victoria Cougars',
    abbr: 'VIC',
    espnAbbr: null,
    color: '#6b3a1d',
    franchiseId: 'victoria',
  },
  {
    year: 1926,
    noChampion: false,
    name: 'Montreal Maroons',
    abbr: 'MMAR',
    espnAbbr: null,
    color: '#6b1d1d',
    franchiseId: 'montreal_mar',
  },

  // NHL Era (1927–2025)
  {
    year: 1927,
    noChampion: false,
    name: 'Ottawa Senators',
    abbr: 'OTT',
    espnAbbr: null,
    color: '#c42b34',
    franchiseId: 'ottawa_og',
  },
  {
    year: 1928,
    noChampion: false,
    name: 'New York Rangers',
    abbr: 'NYR',
    espnAbbr: 'nyr',
    color: '#0038A8',
    franchiseId: 'rangers',
  },
  {
    year: 1929,
    noChampion: false,
    name: 'Boston Bruins',
    abbr: 'BOS',
    espnAbbr: 'bos',
    color: '#FFB81C',
    franchiseId: 'bruins',
  },
  {
    year: 1930,
    noChampion: false,
    name: 'Montreal Canadiens',
    abbr: 'MTL',
    espnAbbr: 'mtl',
    color: '#AF1E2D',
    franchiseId: 'canadiens',
  },
  {
    year: 1931,
    noChampion: false,
    name: 'Montreal Canadiens',
    abbr: 'MTL',
    espnAbbr: 'mtl',
    color: '#AF1E2D',
    franchiseId: 'canadiens',
  },
  {
    year: 1932,
    noChampion: false,
    name: 'Toronto Maple Leafs',
    abbr: 'TOR',
    espnAbbr: 'tor',
    color: '#00539B',
    franchiseId: 'toronto',
  },
  {
    year: 1933,
    noChampion: false,
    name: 'New York Rangers',
    abbr: 'NYR',
    espnAbbr: 'nyr',
    color: '#0038A8',
    franchiseId: 'rangers',
  },
  {
    year: 1934,
    noChampion: false,
    name: 'Chicago Blackhawks',
    abbr: 'CHI',
    espnAbbr: 'chi',
    color: '#CF0A2C',
    franchiseId: 'blackhawks',
  },
  {
    year: 1935,
    noChampion: false,
    name: 'Montreal Maroons',
    abbr: 'MMAR',
    espnAbbr: null,
    color: '#6b1d1d',
    franchiseId: 'montreal_mar',
  },
  {
    year: 1936,
    noChampion: false,
    name: 'Detroit Red Wings',
    abbr: 'DET',
    espnAbbr: 'det',
    color: '#CE1126',
    franchiseId: 'red_wings',
  },
  {
    year: 1937,
    noChampion: false,
    name: 'Detroit Red Wings',
    abbr: 'DET',
    espnAbbr: 'det',
    color: '#CE1126',
    franchiseId: 'red_wings',
  },
  {
    year: 1938,
    noChampion: false,
    name: 'Chicago Blackhawks',
    abbr: 'CHI',
    espnAbbr: 'chi',
    color: '#CF0A2C',
    franchiseId: 'blackhawks',
  },
  {
    year: 1939,
    noChampion: false,
    name: 'Boston Bruins',
    abbr: 'BOS',
    espnAbbr: 'bos',
    color: '#FFB81C',
    franchiseId: 'bruins',
  },
  {
    year: 1940,
    noChampion: false,
    name: 'New York Rangers',
    abbr: 'NYR',
    espnAbbr: 'nyr',
    color: '#0038A8',
    franchiseId: 'rangers',
  },
  {
    year: 1941,
    noChampion: false,
    name: 'Boston Bruins',
    abbr: 'BOS',
    espnAbbr: 'bos',
    color: '#FFB81C',
    franchiseId: 'bruins',
  },
  {
    year: 1942,
    noChampion: false,
    name: 'Toronto Maple Leafs',
    abbr: 'TOR',
    espnAbbr: 'tor',
    color: '#00539B',
    franchiseId: 'toronto',
  },
  {
    year: 1943,
    noChampion: false,
    name: 'Detroit Red Wings',
    abbr: 'DET',
    espnAbbr: 'det',
    color: '#CE1126',
    franchiseId: 'red_wings',
  },
  {
    year: 1944,
    noChampion: false,
    name: 'Montreal Canadiens',
    abbr: 'MTL',
    espnAbbr: 'mtl',
    color: '#AF1E2D',
    franchiseId: 'canadiens',
  },
  {
    year: 1945,
    noChampion: false,
    name: 'Toronto Maple Leafs',
    abbr: 'TOR',
    espnAbbr: 'tor',
    color: '#00539B',
    franchiseId: 'toronto',
  },
  {
    year: 1946,
    noChampion: false,
    name: 'Montreal Canadiens',
    abbr: 'MTL',
    espnAbbr: 'mtl',
    color: '#AF1E2D',
    franchiseId: 'canadiens',
  },
  {
    year: 1947,
    noChampion: false,
    name: 'Toronto Maple Leafs',
    abbr: 'TOR',
    espnAbbr: 'tor',
    color: '#00539B',
    franchiseId: 'toronto',
  },
  {
    year: 1948,
    noChampion: false,
    name: 'Toronto Maple Leafs',
    abbr: 'TOR',
    espnAbbr: 'tor',
    color: '#00539B',
    franchiseId: 'toronto',
  },
  {
    year: 1949,
    noChampion: false,
    name: 'Toronto Maple Leafs',
    abbr: 'TOR',
    espnAbbr: 'tor',
    color: '#00539B',
    franchiseId: 'toronto',
  },
  {
    year: 1950,
    noChampion: false,
    name: 'Detroit Red Wings',
    abbr: 'DET',
    espnAbbr: 'det',
    color: '#CE1126',
    franchiseId: 'red_wings',
  },
  {
    year: 1951,
    noChampion: false,
    name: 'Toronto Maple Leafs',
    abbr: 'TOR',
    espnAbbr: 'tor',
    color: '#00539B',
    franchiseId: 'toronto',
  },
  {
    year: 1952,
    noChampion: false,
    name: 'Detroit Red Wings',
    abbr: 'DET',
    espnAbbr: 'det',
    color: '#CE1126',
    franchiseId: 'red_wings',
  },
  {
    year: 1953,
    noChampion: false,
    name: 'Montreal Canadiens',
    abbr: 'MTL',
    espnAbbr: 'mtl',
    color: '#AF1E2D',
    franchiseId: 'canadiens',
  },
  {
    year: 1954,
    noChampion: false,
    name: 'Detroit Red Wings',
    abbr: 'DET',
    espnAbbr: 'det',
    color: '#CE1126',
    franchiseId: 'red_wings',
  },
  {
    year: 1955,
    noChampion: false,
    name: 'Detroit Red Wings',
    abbr: 'DET',
    espnAbbr: 'det',
    color: '#CE1126',
    franchiseId: 'red_wings',
  },
  {
    year: 1956,
    noChampion: false,
    name: 'Montreal Canadiens',
    abbr: 'MTL',
    espnAbbr: 'mtl',
    color: '#AF1E2D',
    franchiseId: 'canadiens',
  },
  {
    year: 1957,
    noChampion: false,
    name: 'Montreal Canadiens',
    abbr: 'MTL',
    espnAbbr: 'mtl',
    color: '#AF1E2D',
    franchiseId: 'canadiens',
  },
  {
    year: 1958,
    noChampion: false,
    name: 'Montreal Canadiens',
    abbr: 'MTL',
    espnAbbr: 'mtl',
    color: '#AF1E2D',
    franchiseId: 'canadiens',
  },
  {
    year: 1959,
    noChampion: false,
    name: 'Montreal Canadiens',
    abbr: 'MTL',
    espnAbbr: 'mtl',
    color: '#AF1E2D',
    franchiseId: 'canadiens',
  },
  {
    year: 1960,
    noChampion: false,
    name: 'Montreal Canadiens',
    abbr: 'MTL',
    espnAbbr: 'mtl',
    color: '#AF1E2D',
    franchiseId: 'canadiens',
  },
  {
    year: 1961,
    noChampion: false,
    name: 'Chicago Blackhawks',
    abbr: 'CHI',
    espnAbbr: 'chi',
    color: '#CF0A2C',
    franchiseId: 'blackhawks',
  },
  {
    year: 1962,
    noChampion: false,
    name: 'Toronto Maple Leafs',
    abbr: 'TOR',
    espnAbbr: 'tor',
    color: '#00539B',
    franchiseId: 'toronto',
  },
  {
    year: 1963,
    noChampion: false,
    name: 'Toronto Maple Leafs',
    abbr: 'TOR',
    espnAbbr: 'tor',
    color: '#00539B',
    franchiseId: 'toronto',
  },
  {
    year: 1964,
    noChampion: false,
    name: 'Toronto Maple Leafs',
    abbr: 'TOR',
    espnAbbr: 'tor',
    color: '#00539B',
    franchiseId: 'toronto',
  },
  {
    year: 1965,
    noChampion: false,
    name: 'Montreal Canadiens',
    abbr: 'MTL',
    espnAbbr: 'mtl',
    color: '#AF1E2D',
    franchiseId: 'canadiens',
  },
  {
    year: 1966,
    noChampion: false,
    name: 'Montreal Canadiens',
    abbr: 'MTL',
    espnAbbr: 'mtl',
    color: '#AF1E2D',
    franchiseId: 'canadiens',
  },
  {
    year: 1967,
    noChampion: false,
    name: 'Toronto Maple Leafs',
    abbr: 'TOR',
    espnAbbr: 'tor',
    color: '#00539B',
    franchiseId: 'toronto',
  },
  {
    year: 1968,
    noChampion: false,
    name: 'Montreal Canadiens',
    abbr: 'MTL',
    espnAbbr: 'mtl',
    color: '#AF1E2D',
    franchiseId: 'canadiens',
  },
  {
    year: 1969,
    noChampion: false,
    name: 'Montreal Canadiens',
    abbr: 'MTL',
    espnAbbr: 'mtl',
    color: '#AF1E2D',
    franchiseId: 'canadiens',
  },
  {
    year: 1970,
    noChampion: false,
    name: 'Boston Bruins',
    abbr: 'BOS',
    espnAbbr: 'bos',
    color: '#FFB81C',
    franchiseId: 'bruins',
  },
  {
    year: 1971,
    noChampion: false,
    name: 'Montreal Canadiens',
    abbr: 'MTL',
    espnAbbr: 'mtl',
    color: '#AF1E2D',
    franchiseId: 'canadiens',
  },
  {
    year: 1972,
    noChampion: false,
    name: 'Boston Bruins',
    abbr: 'BOS',
    espnAbbr: 'bos',
    color: '#FFB81C',
    franchiseId: 'bruins',
  },
  {
    year: 1973,
    noChampion: false,
    name: 'Montreal Canadiens',
    abbr: 'MTL',
    espnAbbr: 'mtl',
    color: '#AF1E2D',
    franchiseId: 'canadiens',
  },
  {
    year: 1974,
    noChampion: false,
    name: 'Philadelphia Flyers',
    abbr: 'PHI',
    espnAbbr: 'phi',
    color: '#F74902',
    franchiseId: 'flyers',
  },
  {
    year: 1975,
    noChampion: false,
    name: 'Philadelphia Flyers',
    abbr: 'PHI',
    espnAbbr: 'phi',
    color: '#F74902',
    franchiseId: 'flyers',
  },
  {
    year: 1976,
    noChampion: false,
    name: 'Montreal Canadiens',
    abbr: 'MTL',
    espnAbbr: 'mtl',
    color: '#AF1E2D',
    franchiseId: 'canadiens',
  },
  {
    year: 1977,
    noChampion: false,
    name: 'Montreal Canadiens',
    abbr: 'MTL',
    espnAbbr: 'mtl',
    color: '#AF1E2D',
    franchiseId: 'canadiens',
  },
  {
    year: 1978,
    noChampion: false,
    name: 'Montreal Canadiens',
    abbr: 'MTL',
    espnAbbr: 'mtl',
    color: '#AF1E2D',
    franchiseId: 'canadiens',
  },
  {
    year: 1979,
    noChampion: false,
    name: 'Montreal Canadiens',
    abbr: 'MTL',
    espnAbbr: 'mtl',
    color: '#AF1E2D',
    franchiseId: 'canadiens',
  },
  {
    year: 1980,
    noChampion: false,
    name: 'New York Islanders',
    abbr: 'NYI',
    espnAbbr: 'nyi',
    color: '#00539B',
    franchiseId: 'islanders',
  },
  {
    year: 1981,
    noChampion: false,
    name: 'New York Islanders',
    abbr: 'NYI',
    espnAbbr: 'nyi',
    color: '#00539B',
    franchiseId: 'islanders',
  },
  {
    year: 1982,
    noChampion: false,
    name: 'New York Islanders',
    abbr: 'NYI',
    espnAbbr: 'nyi',
    color: '#00539B',
    franchiseId: 'islanders',
  },
  {
    year: 1983,
    noChampion: false,
    name: 'New York Islanders',
    abbr: 'NYI',
    espnAbbr: 'nyi',
    color: '#00539B',
    franchiseId: 'islanders',
  },
  {
    year: 1984,
    noChampion: false,
    name: 'Edmonton Oilers',
    abbr: 'EDM',
    espnAbbr: 'edm',
    color: '#FF4C00',
    franchiseId: 'oilers',
  },
  {
    year: 1985,
    noChampion: false,
    name: 'Edmonton Oilers',
    abbr: 'EDM',
    espnAbbr: 'edm',
    color: '#FF4C00',
    franchiseId: 'oilers',
  },
  {
    year: 1986,
    noChampion: false,
    name: 'Montreal Canadiens',
    abbr: 'MTL',
    espnAbbr: 'mtl',
    color: '#AF1E2D',
    franchiseId: 'canadiens',
  },
  {
    year: 1987,
    noChampion: false,
    name: 'Edmonton Oilers',
    abbr: 'EDM',
    espnAbbr: 'edm',
    color: '#FF4C00',
    franchiseId: 'oilers',
  },
  {
    year: 1988,
    noChampion: false,
    name: 'Edmonton Oilers',
    abbr: 'EDM',
    espnAbbr: 'edm',
    color: '#FF4C00',
    franchiseId: 'oilers',
  },
  {
    year: 1989,
    noChampion: false,
    name: 'Calgary Flames',
    abbr: 'CGY',
    espnAbbr: 'cgy',
    color: '#CE1126',
    franchiseId: 'flames',
  },
  {
    year: 1990,
    noChampion: false,
    name: 'Edmonton Oilers',
    abbr: 'EDM',
    espnAbbr: 'edm',
    color: '#FF4C00',
    franchiseId: 'oilers',
  },
  {
    year: 1991,
    noChampion: false,
    name: 'Pittsburgh Penguins',
    abbr: 'PIT',
    espnAbbr: 'pit',
    color: '#FCB514',
    franchiseId: 'penguins',
  },
  {
    year: 1992,
    noChampion: false,
    name: 'Pittsburgh Penguins',
    abbr: 'PIT',
    espnAbbr: 'pit',
    color: '#FCB514',
    franchiseId: 'penguins',
  },
  {
    year: 1993,
    noChampion: false,
    name: 'Montreal Canadiens',
    abbr: 'MTL',
    espnAbbr: 'mtl',
    color: '#AF1E2D',
    franchiseId: 'canadiens',
  },
  {
    year: 1994,
    noChampion: false,
    name: 'New York Rangers',
    abbr: 'NYR',
    espnAbbr: 'nyr',
    color: '#0038A8',
    franchiseId: 'rangers',
  },
  {
    year: 1995,
    noChampion: false,
    name: 'New Jersey Devils',
    abbr: 'NJD',
    espnAbbr: 'njd',
    color: '#CE1126',
    franchiseId: 'devils',
  },
  {
    year: 1996,
    noChampion: false,
    name: 'Colorado Avalanche',
    abbr: 'COL',
    espnAbbr: 'col',
    color: '#6F263D',
    franchiseId: 'avalanche',
  },
  {
    year: 1997,
    noChampion: false,
    name: 'Detroit Red Wings',
    abbr: 'DET',
    espnAbbr: 'det',
    color: '#CE1126',
    franchiseId: 'red_wings',
  },
  {
    year: 1998,
    noChampion: false,
    name: 'Detroit Red Wings',
    abbr: 'DET',
    espnAbbr: 'det',
    color: '#CE1126',
    franchiseId: 'red_wings',
  },
  {
    year: 1999,
    noChampion: false,
    name: 'Dallas Stars',
    abbr: 'DAL',
    espnAbbr: 'dal',
    color: '#006847',
    franchiseId: 'stars',
  },
  {
    year: 2000,
    noChampion: false,
    name: 'New Jersey Devils',
    abbr: 'NJD',
    espnAbbr: 'njd',
    color: '#CE1126',
    franchiseId: 'devils',
  },
  {
    year: 2001,
    noChampion: false,
    name: 'Colorado Avalanche',
    abbr: 'COL',
    espnAbbr: 'col',
    color: '#6F263D',
    franchiseId: 'avalanche',
  },
  {
    year: 2002,
    noChampion: false,
    name: 'Detroit Red Wings',
    abbr: 'DET',
    espnAbbr: 'det',
    color: '#CE1126',
    franchiseId: 'red_wings',
  },
  {
    year: 2003,
    noChampion: false,
    name: 'New Jersey Devils',
    abbr: 'NJD',
    espnAbbr: 'njd',
    color: '#CE1126',
    franchiseId: 'devils',
  },
  {
    year: 2004,
    noChampion: false,
    name: 'Tampa Bay Lightning',
    abbr: 'TBL',
    espnAbbr: 'tb',
    color: '#002868',
    franchiseId: 'lightning',
  },
  { year: 2005, noChampion: true, reason: 'lockout' },
  {
    year: 2006,
    noChampion: false,
    name: 'Carolina Hurricanes',
    abbr: 'CAR',
    espnAbbr: 'car',
    color: '#CC0000',
    franchiseId: 'hurricanes',
  },
  {
    year: 2007,
    noChampion: false,
    name: 'Anaheim Ducks',
    abbr: 'ANA',
    espnAbbr: 'ana',
    color: '#F47A38',
    franchiseId: 'ducks',
  },
  {
    year: 2008,
    noChampion: false,
    name: 'Detroit Red Wings',
    abbr: 'DET',
    espnAbbr: 'det',
    color: '#CE1126',
    franchiseId: 'red_wings',
  },
  {
    year: 2009,
    noChampion: false,
    name: 'Pittsburgh Penguins',
    abbr: 'PIT',
    espnAbbr: 'pit',
    color: '#FCB514',
    franchiseId: 'penguins',
  },
  {
    year: 2010,
    noChampion: false,
    name: 'Chicago Blackhawks',
    abbr: 'CHI',
    espnAbbr: 'chi',
    color: '#CF0A2C',
    franchiseId: 'blackhawks',
  },
  {
    year: 2011,
    noChampion: false,
    name: 'Boston Bruins',
    abbr: 'BOS',
    espnAbbr: 'bos',
    color: '#FFB81C',
    franchiseId: 'bruins',
  },
  {
    year: 2012,
    noChampion: false,
    name: 'Los Angeles Kings',
    abbr: 'LAK',
    espnAbbr: 'la',
    color: '#A2AAAD',
    franchiseId: 'kings',
  },
  {
    year: 2013,
    noChampion: false,
    name: 'Chicago Blackhawks',
    abbr: 'CHI',
    espnAbbr: 'chi',
    color: '#CF0A2C',
    franchiseId: 'blackhawks',
  },
  {
    year: 2014,
    noChampion: false,
    name: 'Los Angeles Kings',
    abbr: 'LAK',
    espnAbbr: 'la',
    color: '#A2AAAD',
    franchiseId: 'kings',
  },
  {
    year: 2015,
    noChampion: false,
    name: 'Chicago Blackhawks',
    abbr: 'CHI',
    espnAbbr: 'chi',
    color: '#CF0A2C',
    franchiseId: 'blackhawks',
  },
  {
    year: 2016,
    noChampion: false,
    name: 'Pittsburgh Penguins',
    abbr: 'PIT',
    espnAbbr: 'pit',
    color: '#FCB514',
    franchiseId: 'penguins',
  },
  {
    year: 2017,
    noChampion: false,
    name: 'Pittsburgh Penguins',
    abbr: 'PIT',
    espnAbbr: 'pit',
    color: '#FCB514',
    franchiseId: 'penguins',
  },
  {
    year: 2018,
    noChampion: false,
    name: 'Washington Capitals',
    abbr: 'WSH',
    espnAbbr: 'wsh',
    color: '#C8102E',
    franchiseId: 'capitals',
  },
  {
    year: 2019,
    noChampion: false,
    name: 'St. Louis Blues',
    abbr: 'STL',
    espnAbbr: 'stl',
    color: '#002F87',
    franchiseId: 'blues',
  },
  {
    year: 2020,
    noChampion: false,
    name: 'Tampa Bay Lightning',
    abbr: 'TBL',
    espnAbbr: 'tb',
    color: '#002868',
    franchiseId: 'lightning',
  },
  {
    year: 2021,
    noChampion: false,
    name: 'Tampa Bay Lightning',
    abbr: 'TBL',
    espnAbbr: 'tb',
    color: '#002868',
    franchiseId: 'lightning',
  },
  {
    year: 2022,
    noChampion: false,
    name: 'Colorado Avalanche',
    abbr: 'COL',
    espnAbbr: 'col',
    color: '#6F263D',
    franchiseId: 'avalanche',
  },
  {
    year: 2023,
    noChampion: false,
    name: 'Vegas Golden Knights',
    abbr: 'VGK',
    espnAbbr: 'vgs',
    color: '#B4975A',
    franchiseId: 'golden_knights',
  },
  {
    year: 2024,
    noChampion: false,
    name: 'Florida Panthers',
    abbr: 'FLA',
    espnAbbr: 'fla',
    color: '#C8102E',
    franchiseId: 'panthers',
  },
  {
    year: 2025,
    noChampion: false,
    name: 'Florida Panthers',
    abbr: 'FLA',
    espnAbbr: 'fla',
    color: '#C8102E',
    franchiseId: 'panthers',
  },
];
