// English top-flight champion dataset.
// Covers the Football League First Division (1888-89 -> 1991-92) and
// the Premier League (1992-93 -> present). Each row's competitionLabel
// carries the era name so ChampionRow shows a small chip - readers can
// see that Man United's 20 titles span both eras (7 First Division +
// 13 Premier League through 2013).
//
// Each row's `year` is the year the season ENDED. So the inaugural
// 1888-89 season = year 1889; the 2023-24 Premier League = year 2024.
//
// World-war suspensions render as noChampion rows:
//   - 1916-1919 (WWI): 4 rows. The 1914-15 season completed (Everton,
//     year 1915) before league football was suspended; play resumed
//     with the 1919-20 season (year 1920).
//   - 1940-1946 (WWII): 7 rows. The 1938-39 season completed (Everton,
//     year 1939); play resumed with the 1946-47 season (year 1947).
//
// No franchise relocations - English clubs are geographically stable -
// so each club has one stable franchiseId. Sheffield Wednesday's 1903
// and 1904 titles were earned under the club's earlier name "The
// Wednesday"; both roll up via the `sheff_wed` id.
//
// espnAbbr is null for every row: EPL doesn't have a public logo CDN
// we can reliably hit, so TeamLogo falls straight through to the text
// badge tier. Leeds uses the away-kit navy (#1D428A) rather than pure
// white so the text-badge luma heuristic reads correctly on a white
// background.

import type { Row } from '../../shared/types';

export const CHAMPIONS: Row[] = [
  {
    year: 1889,
    noChampion: false,
    name: 'Preston North End',
    abbr: 'PNE',
    espnAbbr: null,
    color: '#B2B2B2',
    franchiseId: 'preston',
    competitionLabel: 'First Division',
  },
  {
    year: 1890,
    noChampion: false,
    name: 'Preston North End',
    abbr: 'PNE',
    espnAbbr: null,
    color: '#B2B2B2',
    franchiseId: 'preston',
    competitionLabel: 'First Division',
  },
  {
    year: 1891,
    noChampion: false,
    name: 'Everton',
    abbr: 'EVE',
    espnAbbr: null,
    color: '#003399',
    franchiseId: 'everton',
    competitionLabel: 'First Division',
  },
  {
    year: 1892,
    noChampion: false,
    name: 'Sunderland',
    abbr: 'SUN',
    espnAbbr: null,
    color: '#EB172B',
    franchiseId: 'sunderland',
    competitionLabel: 'First Division',
  },
  {
    year: 1893,
    noChampion: false,
    name: 'Sunderland',
    abbr: 'SUN',
    espnAbbr: null,
    color: '#EB172B',
    franchiseId: 'sunderland',
    competitionLabel: 'First Division',
  },
  {
    year: 1894,
    noChampion: false,
    name: 'Aston Villa',
    abbr: 'AVL',
    espnAbbr: null,
    color: '#670E36',
    franchiseId: 'aston_villa',
    competitionLabel: 'First Division',
  },
  {
    year: 1895,
    noChampion: false,
    name: 'Sunderland',
    abbr: 'SUN',
    espnAbbr: null,
    color: '#EB172B',
    franchiseId: 'sunderland',
    competitionLabel: 'First Division',
  },
  {
    year: 1896,
    noChampion: false,
    name: 'Aston Villa',
    abbr: 'AVL',
    espnAbbr: null,
    color: '#670E36',
    franchiseId: 'aston_villa',
    competitionLabel: 'First Division',
  },
  {
    year: 1897,
    noChampion: false,
    name: 'Aston Villa',
    abbr: 'AVL',
    espnAbbr: null,
    color: '#670E36',
    franchiseId: 'aston_villa',
    competitionLabel: 'First Division',
  },
  {
    year: 1898,
    noChampion: false,
    name: 'Sheffield United',
    abbr: 'SHU',
    espnAbbr: null,
    color: '#EE2737',
    franchiseId: 'sheff_united',
    competitionLabel: 'First Division',
  },
  {
    year: 1899,
    noChampion: false,
    name: 'Aston Villa',
    abbr: 'AVL',
    espnAbbr: null,
    color: '#670E36',
    franchiseId: 'aston_villa',
    competitionLabel: 'First Division',
  },
  {
    year: 1900,
    noChampion: false,
    name: 'Aston Villa',
    abbr: 'AVL',
    espnAbbr: null,
    color: '#670E36',
    franchiseId: 'aston_villa',
    competitionLabel: 'First Division',
  },
  {
    year: 1901,
    noChampion: false,
    name: 'Liverpool',
    abbr: 'LIV',
    espnAbbr: null,
    color: '#C8102E',
    franchiseId: 'liverpool',
    competitionLabel: 'First Division',
  },
  {
    year: 1902,
    noChampion: false,
    name: 'Sunderland',
    abbr: 'SUN',
    espnAbbr: null,
    color: '#EB172B',
    franchiseId: 'sunderland',
    competitionLabel: 'First Division',
  },
  {
    year: 1903,
    noChampion: false,
    // Era-accurate name: the club competed as "The Wednesday" until 1929
    // when it officially became Sheffield Wednesday. Rolls up via the
    // modern `sheff_wed` id.
    name: 'The Wednesday',
    abbr: 'SHW',
    espnAbbr: null,
    color: '#1D44A6',
    franchiseId: 'sheff_wed',
    competitionLabel: 'First Division',
  },
  {
    year: 1904,
    noChampion: false,
    name: 'The Wednesday',
    abbr: 'SHW',
    espnAbbr: null,
    color: '#1D44A6',
    franchiseId: 'sheff_wed',
    competitionLabel: 'First Division',
  },
  {
    year: 1905,
    noChampion: false,
    name: 'Newcastle United',
    abbr: 'NEW',
    espnAbbr: null,
    color: '#241F20',
    franchiseId: 'newcastle',
    competitionLabel: 'First Division',
  },
  {
    year: 1906,
    noChampion: false,
    name: 'Liverpool',
    abbr: 'LIV',
    espnAbbr: null,
    color: '#C8102E',
    franchiseId: 'liverpool',
    competitionLabel: 'First Division',
  },
  {
    year: 1907,
    noChampion: false,
    name: 'Newcastle United',
    abbr: 'NEW',
    espnAbbr: null,
    color: '#241F20',
    franchiseId: 'newcastle',
    competitionLabel: 'First Division',
  },
  {
    year: 1908,
    noChampion: false,
    name: 'Manchester United',
    abbr: 'MUN',
    espnAbbr: null,
    color: '#DA291C',
    franchiseId: 'man_united',
    competitionLabel: 'First Division',
  },
  {
    year: 1909,
    noChampion: false,
    name: 'Newcastle United',
    abbr: 'NEW',
    espnAbbr: null,
    color: '#241F20',
    franchiseId: 'newcastle',
    competitionLabel: 'First Division',
  },
  {
    year: 1910,
    noChampion: false,
    name: 'Aston Villa',
    abbr: 'AVL',
    espnAbbr: null,
    color: '#670E36',
    franchiseId: 'aston_villa',
    competitionLabel: 'First Division',
  },
  {
    year: 1911,
    noChampion: false,
    name: 'Manchester United',
    abbr: 'MUN',
    espnAbbr: null,
    color: '#DA291C',
    franchiseId: 'man_united',
    competitionLabel: 'First Division',
  },
  {
    year: 1912,
    noChampion: false,
    name: 'Blackburn Rovers',
    abbr: 'BLB',
    espnAbbr: null,
    color: '#009EE0',
    franchiseId: 'blackburn',
    competitionLabel: 'First Division',
  },
  {
    year: 1913,
    noChampion: false,
    name: 'Sunderland',
    abbr: 'SUN',
    espnAbbr: null,
    color: '#EB172B',
    franchiseId: 'sunderland',
    competitionLabel: 'First Division',
  },
  {
    year: 1914,
    noChampion: false,
    name: 'Blackburn Rovers',
    abbr: 'BLB',
    espnAbbr: null,
    color: '#009EE0',
    franchiseId: 'blackburn',
    competitionLabel: 'First Division',
  },
  {
    year: 1915,
    noChampion: false,
    name: 'Everton',
    abbr: 'EVE',
    espnAbbr: null,
    color: '#003399',
    franchiseId: 'everton',
    competitionLabel: 'First Division',
  },
  { year: 1916, noChampion: true, reason: 'World War I' },
  { year: 1917, noChampion: true, reason: 'World War I' },
  { year: 1918, noChampion: true, reason: 'World War I' },
  { year: 1919, noChampion: true, reason: 'World War I' },
  {
    year: 1920,
    noChampion: false,
    name: 'West Bromwich Albion',
    abbr: 'WBA',
    espnAbbr: null,
    color: '#122F67',
    franchiseId: 'west_brom',
    competitionLabel: 'First Division',
  },
  {
    year: 1921,
    noChampion: false,
    name: 'Burnley',
    abbr: 'BUR',
    espnAbbr: null,
    color: '#6C1D45',
    franchiseId: 'burnley',
    competitionLabel: 'First Division',
  },
  {
    year: 1922,
    noChampion: false,
    name: 'Liverpool',
    abbr: 'LIV',
    espnAbbr: null,
    color: '#C8102E',
    franchiseId: 'liverpool',
    competitionLabel: 'First Division',
  },
  {
    year: 1923,
    noChampion: false,
    name: 'Liverpool',
    abbr: 'LIV',
    espnAbbr: null,
    color: '#C8102E',
    franchiseId: 'liverpool',
    competitionLabel: 'First Division',
  },
  {
    year: 1924,
    noChampion: false,
    name: 'Huddersfield Town',
    abbr: 'HUD',
    espnAbbr: null,
    color: '#0E63AD',
    franchiseId: 'huddersfield',
    competitionLabel: 'First Division',
  },
  {
    year: 1925,
    noChampion: false,
    name: 'Huddersfield Town',
    abbr: 'HUD',
    espnAbbr: null,
    color: '#0E63AD',
    franchiseId: 'huddersfield',
    competitionLabel: 'First Division',
  },
  {
    year: 1926,
    noChampion: false,
    name: 'Huddersfield Town',
    abbr: 'HUD',
    espnAbbr: null,
    color: '#0E63AD',
    franchiseId: 'huddersfield',
    competitionLabel: 'First Division',
  },
  {
    year: 1927,
    noChampion: false,
    name: 'Newcastle United',
    abbr: 'NEW',
    espnAbbr: null,
    color: '#241F20',
    franchiseId: 'newcastle',
    competitionLabel: 'First Division',
  },
  {
    year: 1928,
    noChampion: false,
    name: 'Everton',
    abbr: 'EVE',
    espnAbbr: null,
    color: '#003399',
    franchiseId: 'everton',
    competitionLabel: 'First Division',
  },
  {
    year: 1929,
    noChampion: false,
    name: 'Sheffield Wednesday',
    abbr: 'SHW',
    espnAbbr: null,
    color: '#1D44A6',
    franchiseId: 'sheff_wed',
    competitionLabel: 'First Division',
  },
  {
    year: 1930,
    noChampion: false,
    name: 'Sheffield Wednesday',
    abbr: 'SHW',
    espnAbbr: null,
    color: '#1D44A6',
    franchiseId: 'sheff_wed',
    competitionLabel: 'First Division',
  },
  {
    year: 1931,
    noChampion: false,
    name: 'Arsenal',
    abbr: 'ARS',
    espnAbbr: null,
    color: '#EF0107',
    franchiseId: 'arsenal',
    competitionLabel: 'First Division',
  },
  {
    year: 1932,
    noChampion: false,
    name: 'Everton',
    abbr: 'EVE',
    espnAbbr: null,
    color: '#003399',
    franchiseId: 'everton',
    competitionLabel: 'First Division',
  },
  {
    year: 1933,
    noChampion: false,
    name: 'Arsenal',
    abbr: 'ARS',
    espnAbbr: null,
    color: '#EF0107',
    franchiseId: 'arsenal',
    competitionLabel: 'First Division',
  },
  {
    year: 1934,
    noChampion: false,
    name: 'Arsenal',
    abbr: 'ARS',
    espnAbbr: null,
    color: '#EF0107',
    franchiseId: 'arsenal',
    competitionLabel: 'First Division',
  },
  {
    year: 1935,
    noChampion: false,
    name: 'Arsenal',
    abbr: 'ARS',
    espnAbbr: null,
    color: '#EF0107',
    franchiseId: 'arsenal',
    competitionLabel: 'First Division',
  },
  {
    year: 1936,
    noChampion: false,
    name: 'Sunderland',
    abbr: 'SUN',
    espnAbbr: null,
    color: '#EB172B',
    franchiseId: 'sunderland',
    competitionLabel: 'First Division',
  },
  {
    year: 1937,
    noChampion: false,
    name: 'Manchester City',
    abbr: 'MCI',
    espnAbbr: null,
    color: '#6CABDD',
    franchiseId: 'man_city',
    competitionLabel: 'First Division',
  },
  {
    year: 1938,
    noChampion: false,
    name: 'Arsenal',
    abbr: 'ARS',
    espnAbbr: null,
    color: '#EF0107',
    franchiseId: 'arsenal',
    competitionLabel: 'First Division',
  },
  {
    year: 1939,
    noChampion: false,
    name: 'Everton',
    abbr: 'EVE',
    espnAbbr: null,
    color: '#003399',
    franchiseId: 'everton',
    competitionLabel: 'First Division',
  },
  { year: 1940, noChampion: true, reason: 'World War II' },
  { year: 1941, noChampion: true, reason: 'World War II' },
  { year: 1942, noChampion: true, reason: 'World War II' },
  { year: 1943, noChampion: true, reason: 'World War II' },
  { year: 1944, noChampion: true, reason: 'World War II' },
  { year: 1945, noChampion: true, reason: 'World War II' },
  { year: 1946, noChampion: true, reason: 'World War II' },
  {
    year: 1947,
    noChampion: false,
    name: 'Liverpool',
    abbr: 'LIV',
    espnAbbr: null,
    color: '#C8102E',
    franchiseId: 'liverpool',
    competitionLabel: 'First Division',
  },
  {
    year: 1948,
    noChampion: false,
    name: 'Arsenal',
    abbr: 'ARS',
    espnAbbr: null,
    color: '#EF0107',
    franchiseId: 'arsenal',
    competitionLabel: 'First Division',
  },
  {
    year: 1949,
    noChampion: false,
    name: 'Portsmouth',
    abbr: 'POR',
    espnAbbr: null,
    color: '#002F86',
    franchiseId: 'portsmouth',
    competitionLabel: 'First Division',
  },
  {
    year: 1950,
    noChampion: false,
    name: 'Portsmouth',
    abbr: 'POR',
    espnAbbr: null,
    color: '#002F86',
    franchiseId: 'portsmouth',
    competitionLabel: 'First Division',
  },
  {
    year: 1951,
    noChampion: false,
    name: 'Tottenham Hotspur',
    abbr: 'TOT',
    espnAbbr: null,
    color: '#132257',
    franchiseId: 'tottenham',
    competitionLabel: 'First Division',
  },
  {
    year: 1952,
    noChampion: false,
    name: 'Manchester United',
    abbr: 'MUN',
    espnAbbr: null,
    color: '#DA291C',
    franchiseId: 'man_united',
    competitionLabel: 'First Division',
  },
  {
    year: 1953,
    noChampion: false,
    name: 'Arsenal',
    abbr: 'ARS',
    espnAbbr: null,
    color: '#EF0107',
    franchiseId: 'arsenal',
    competitionLabel: 'First Division',
  },
  {
    year: 1954,
    noChampion: false,
    name: 'Wolverhampton Wanderers',
    abbr: 'WOL',
    espnAbbr: null,
    color: '#FDB913',
    franchiseId: 'wolves',
    competitionLabel: 'First Division',
  },
  {
    year: 1955,
    noChampion: false,
    name: 'Chelsea',
    abbr: 'CHE',
    espnAbbr: null,
    color: '#034694',
    franchiseId: 'chelsea',
    competitionLabel: 'First Division',
  },
  {
    year: 1956,
    noChampion: false,
    name: 'Manchester United',
    abbr: 'MUN',
    espnAbbr: null,
    color: '#DA291C',
    franchiseId: 'man_united',
    competitionLabel: 'First Division',
  },
  {
    year: 1957,
    noChampion: false,
    name: 'Manchester United',
    abbr: 'MUN',
    espnAbbr: null,
    color: '#DA291C',
    franchiseId: 'man_united',
    competitionLabel: 'First Division',
  },
  {
    year: 1958,
    noChampion: false,
    name: 'Wolverhampton Wanderers',
    abbr: 'WOL',
    espnAbbr: null,
    color: '#FDB913',
    franchiseId: 'wolves',
    competitionLabel: 'First Division',
  },
  {
    year: 1959,
    noChampion: false,
    name: 'Wolverhampton Wanderers',
    abbr: 'WOL',
    espnAbbr: null,
    color: '#FDB913',
    franchiseId: 'wolves',
    competitionLabel: 'First Division',
  },
  {
    year: 1960,
    noChampion: false,
    name: 'Burnley',
    abbr: 'BUR',
    espnAbbr: null,
    color: '#6C1D45',
    franchiseId: 'burnley',
    competitionLabel: 'First Division',
  },
  {
    year: 1961,
    noChampion: false,
    name: 'Tottenham Hotspur',
    abbr: 'TOT',
    espnAbbr: null,
    color: '#132257',
    franchiseId: 'tottenham',
    competitionLabel: 'First Division',
  },
  {
    year: 1962,
    noChampion: false,
    name: 'Ipswich Town',
    abbr: 'IPS',
    espnAbbr: null,
    color: '#3E6CA4',
    franchiseId: 'ipswich',
    competitionLabel: 'First Division',
  },
  {
    year: 1963,
    noChampion: false,
    name: 'Everton',
    abbr: 'EVE',
    espnAbbr: null,
    color: '#003399',
    franchiseId: 'everton',
    competitionLabel: 'First Division',
  },
  {
    year: 1964,
    noChampion: false,
    name: 'Liverpool',
    abbr: 'LIV',
    espnAbbr: null,
    color: '#C8102E',
    franchiseId: 'liverpool',
    competitionLabel: 'First Division',
  },
  {
    year: 1965,
    noChampion: false,
    name: 'Manchester United',
    abbr: 'MUN',
    espnAbbr: null,
    color: '#DA291C',
    franchiseId: 'man_united',
    competitionLabel: 'First Division',
  },
  {
    year: 1966,
    noChampion: false,
    name: 'Liverpool',
    abbr: 'LIV',
    espnAbbr: null,
    color: '#C8102E',
    franchiseId: 'liverpool',
    competitionLabel: 'First Division',
  },
  {
    year: 1967,
    noChampion: false,
    name: 'Manchester United',
    abbr: 'MUN',
    espnAbbr: null,
    color: '#DA291C',
    franchiseId: 'man_united',
    competitionLabel: 'First Division',
  },
  {
    year: 1968,
    noChampion: false,
    name: 'Manchester City',
    abbr: 'MCI',
    espnAbbr: null,
    color: '#6CABDD',
    franchiseId: 'man_city',
    competitionLabel: 'First Division',
  },
  {
    year: 1969,
    noChampion: false,
    name: 'Leeds United',
    abbr: 'LEE',
    espnAbbr: null,
    // Leeds' primary white clashes with the white app background, so
    // the text-badge would render invisibly. Use the away-kit navy so
    // the Rec. 601 luma heuristic in TeamLogo picks white badge text.
    color: '#1D428A',
    franchiseId: 'leeds',
    competitionLabel: 'First Division',
  },
  {
    year: 1970,
    noChampion: false,
    name: 'Everton',
    abbr: 'EVE',
    espnAbbr: null,
    color: '#003399',
    franchiseId: 'everton',
    competitionLabel: 'First Division',
  },
  {
    year: 1971,
    noChampion: false,
    name: 'Arsenal',
    abbr: 'ARS',
    espnAbbr: null,
    color: '#EF0107',
    franchiseId: 'arsenal',
    competitionLabel: 'First Division',
  },
  {
    year: 1972,
    noChampion: false,
    name: 'Derby County',
    abbr: 'DER',
    espnAbbr: null,
    color: '#000000',
    franchiseId: 'derby',
    competitionLabel: 'First Division',
  },
  {
    year: 1973,
    noChampion: false,
    name: 'Liverpool',
    abbr: 'LIV',
    espnAbbr: null,
    color: '#C8102E',
    franchiseId: 'liverpool',
    competitionLabel: 'First Division',
  },
  {
    year: 1974,
    noChampion: false,
    name: 'Leeds United',
    abbr: 'LEE',
    espnAbbr: null,
    color: '#1D428A',
    franchiseId: 'leeds',
    competitionLabel: 'First Division',
  },
  {
    year: 1975,
    noChampion: false,
    name: 'Derby County',
    abbr: 'DER',
    espnAbbr: null,
    color: '#000000',
    franchiseId: 'derby',
    competitionLabel: 'First Division',
  },
  {
    year: 1976,
    noChampion: false,
    name: 'Liverpool',
    abbr: 'LIV',
    espnAbbr: null,
    color: '#C8102E',
    franchiseId: 'liverpool',
    competitionLabel: 'First Division',
  },
  {
    year: 1977,
    noChampion: false,
    name: 'Liverpool',
    abbr: 'LIV',
    espnAbbr: null,
    color: '#C8102E',
    franchiseId: 'liverpool',
    competitionLabel: 'First Division',
  },
  {
    year: 1978,
    noChampion: false,
    name: 'Nottingham Forest',
    abbr: 'NFO',
    espnAbbr: null,
    color: '#DD0000',
    franchiseId: 'forest',
    competitionLabel: 'First Division',
  },
  {
    year: 1979,
    noChampion: false,
    name: 'Liverpool',
    abbr: 'LIV',
    espnAbbr: null,
    color: '#C8102E',
    franchiseId: 'liverpool',
    competitionLabel: 'First Division',
  },
  {
    year: 1980,
    noChampion: false,
    name: 'Liverpool',
    abbr: 'LIV',
    espnAbbr: null,
    color: '#C8102E',
    franchiseId: 'liverpool',
    competitionLabel: 'First Division',
  },
  {
    year: 1981,
    noChampion: false,
    name: 'Aston Villa',
    abbr: 'AVL',
    espnAbbr: null,
    color: '#670E36',
    franchiseId: 'aston_villa',
    competitionLabel: 'First Division',
  },
  {
    year: 1982,
    noChampion: false,
    name: 'Liverpool',
    abbr: 'LIV',
    espnAbbr: null,
    color: '#C8102E',
    franchiseId: 'liverpool',
    competitionLabel: 'First Division',
  },
  {
    year: 1983,
    noChampion: false,
    name: 'Liverpool',
    abbr: 'LIV',
    espnAbbr: null,
    color: '#C8102E',
    franchiseId: 'liverpool',
    competitionLabel: 'First Division',
  },
  {
    year: 1984,
    noChampion: false,
    name: 'Liverpool',
    abbr: 'LIV',
    espnAbbr: null,
    color: '#C8102E',
    franchiseId: 'liverpool',
    competitionLabel: 'First Division',
  },
  {
    year: 1985,
    noChampion: false,
    name: 'Everton',
    abbr: 'EVE',
    espnAbbr: null,
    color: '#003399',
    franchiseId: 'everton',
    competitionLabel: 'First Division',
  },
  {
    year: 1986,
    noChampion: false,
    name: 'Liverpool',
    abbr: 'LIV',
    espnAbbr: null,
    color: '#C8102E',
    franchiseId: 'liverpool',
    competitionLabel: 'First Division',
  },
  {
    year: 1987,
    noChampion: false,
    name: 'Everton',
    abbr: 'EVE',
    espnAbbr: null,
    color: '#003399',
    franchiseId: 'everton',
    competitionLabel: 'First Division',
  },
  {
    year: 1988,
    noChampion: false,
    name: 'Liverpool',
    abbr: 'LIV',
    espnAbbr: null,
    color: '#C8102E',
    franchiseId: 'liverpool',
    competitionLabel: 'First Division',
  },
  {
    year: 1989,
    noChampion: false,
    name: 'Arsenal',
    abbr: 'ARS',
    espnAbbr: null,
    color: '#EF0107',
    franchiseId: 'arsenal',
    competitionLabel: 'First Division',
  },
  {
    year: 1990,
    noChampion: false,
    name: 'Liverpool',
    abbr: 'LIV',
    espnAbbr: null,
    color: '#C8102E',
    franchiseId: 'liverpool',
    competitionLabel: 'First Division',
  },
  {
    year: 1991,
    noChampion: false,
    name: 'Arsenal',
    abbr: 'ARS',
    espnAbbr: null,
    color: '#EF0107',
    franchiseId: 'arsenal',
    competitionLabel: 'First Division',
  },
  {
    year: 1992,
    noChampion: false,
    // LAST First Division champion before the Premier League rebrand.
    name: 'Leeds United',
    abbr: 'LEE',
    espnAbbr: null,
    color: '#1D428A',
    franchiseId: 'leeds',
    competitionLabel: 'First Division',
  },
  {
    year: 1993,
    noChampion: false,
    // FIRST Premier League champion (1992-93 season).
    name: 'Manchester United',
    abbr: 'MUN',
    espnAbbr: null,
    color: '#DA291C',
    franchiseId: 'man_united',
    competitionLabel: 'Premier League',
  },
  {
    year: 1994,
    noChampion: false,
    name: 'Manchester United',
    abbr: 'MUN',
    espnAbbr: null,
    color: '#DA291C',
    franchiseId: 'man_united',
    competitionLabel: 'Premier League',
  },
  {
    year: 1995,
    noChampion: false,
    name: 'Blackburn Rovers',
    abbr: 'BLB',
    espnAbbr: null,
    color: '#009EE0',
    franchiseId: 'blackburn',
    competitionLabel: 'Premier League',
  },
  {
    year: 1996,
    noChampion: false,
    name: 'Manchester United',
    abbr: 'MUN',
    espnAbbr: null,
    color: '#DA291C',
    franchiseId: 'man_united',
    competitionLabel: 'Premier League',
  },
  {
    year: 1997,
    noChampion: false,
    name: 'Manchester United',
    abbr: 'MUN',
    espnAbbr: null,
    color: '#DA291C',
    franchiseId: 'man_united',
    competitionLabel: 'Premier League',
  },
  {
    year: 1998,
    noChampion: false,
    name: 'Arsenal',
    abbr: 'ARS',
    espnAbbr: null,
    color: '#EF0107',
    franchiseId: 'arsenal',
    competitionLabel: 'Premier League',
  },
  {
    year: 1999,
    noChampion: false,
    name: 'Manchester United',
    abbr: 'MUN',
    espnAbbr: null,
    color: '#DA291C',
    franchiseId: 'man_united',
    competitionLabel: 'Premier League',
  },
  {
    year: 2000,
    noChampion: false,
    name: 'Manchester United',
    abbr: 'MUN',
    espnAbbr: null,
    color: '#DA291C',
    franchiseId: 'man_united',
    competitionLabel: 'Premier League',
  },
  {
    year: 2001,
    noChampion: false,
    name: 'Manchester United',
    abbr: 'MUN',
    espnAbbr: null,
    color: '#DA291C',
    franchiseId: 'man_united',
    competitionLabel: 'Premier League',
  },
  {
    year: 2002,
    noChampion: false,
    name: 'Arsenal',
    abbr: 'ARS',
    espnAbbr: null,
    color: '#EF0107',
    franchiseId: 'arsenal',
    competitionLabel: 'Premier League',
  },
  {
    year: 2003,
    noChampion: false,
    name: 'Manchester United',
    abbr: 'MUN',
    espnAbbr: null,
    color: '#DA291C',
    franchiseId: 'man_united',
    competitionLabel: 'Premier League',
  },
  {
    year: 2004,
    noChampion: false,
    name: 'Arsenal',
    abbr: 'ARS',
    espnAbbr: null,
    color: '#EF0107',
    franchiseId: 'arsenal',
    competitionLabel: 'Premier League',
  },
  {
    year: 2005,
    noChampion: false,
    name: 'Chelsea',
    abbr: 'CHE',
    espnAbbr: null,
    color: '#034694',
    franchiseId: 'chelsea',
    competitionLabel: 'Premier League',
  },
  {
    year: 2006,
    noChampion: false,
    name: 'Chelsea',
    abbr: 'CHE',
    espnAbbr: null,
    color: '#034694',
    franchiseId: 'chelsea',
    competitionLabel: 'Premier League',
  },
  {
    year: 2007,
    noChampion: false,
    name: 'Manchester United',
    abbr: 'MUN',
    espnAbbr: null,
    color: '#DA291C',
    franchiseId: 'man_united',
    competitionLabel: 'Premier League',
  },
  {
    year: 2008,
    noChampion: false,
    name: 'Manchester United',
    abbr: 'MUN',
    espnAbbr: null,
    color: '#DA291C',
    franchiseId: 'man_united',
    competitionLabel: 'Premier League',
  },
  {
    year: 2009,
    noChampion: false,
    name: 'Manchester United',
    abbr: 'MUN',
    espnAbbr: null,
    color: '#DA291C',
    franchiseId: 'man_united',
    competitionLabel: 'Premier League',
  },
  {
    year: 2010,
    noChampion: false,
    name: 'Chelsea',
    abbr: 'CHE',
    espnAbbr: null,
    color: '#034694',
    franchiseId: 'chelsea',
    competitionLabel: 'Premier League',
  },
  {
    year: 2011,
    noChampion: false,
    name: 'Manchester United',
    abbr: 'MUN',
    espnAbbr: null,
    color: '#DA291C',
    franchiseId: 'man_united',
    competitionLabel: 'Premier League',
  },
  {
    year: 2012,
    noChampion: false,
    name: 'Manchester City',
    abbr: 'MCI',
    espnAbbr: null,
    color: '#6CABDD',
    franchiseId: 'man_city',
    competitionLabel: 'Premier League',
  },
  {
    year: 2013,
    noChampion: false,
    name: 'Manchester United',
    abbr: 'MUN',
    espnAbbr: null,
    color: '#DA291C',
    franchiseId: 'man_united',
    competitionLabel: 'Premier League',
  },
  {
    year: 2014,
    noChampion: false,
    name: 'Manchester City',
    abbr: 'MCI',
    espnAbbr: null,
    color: '#6CABDD',
    franchiseId: 'man_city',
    competitionLabel: 'Premier League',
  },
  {
    year: 2015,
    noChampion: false,
    name: 'Chelsea',
    abbr: 'CHE',
    espnAbbr: null,
    color: '#034694',
    franchiseId: 'chelsea',
    competitionLabel: 'Premier League',
  },
  {
    year: 2016,
    noChampion: false,
    name: 'Leicester City',
    abbr: 'LEI',
    espnAbbr: null,
    color: '#003090',
    franchiseId: 'leicester',
    competitionLabel: 'Premier League',
  },
  {
    year: 2017,
    noChampion: false,
    name: 'Chelsea',
    abbr: 'CHE',
    espnAbbr: null,
    color: '#034694',
    franchiseId: 'chelsea',
    competitionLabel: 'Premier League',
  },
  {
    year: 2018,
    noChampion: false,
    name: 'Manchester City',
    abbr: 'MCI',
    espnAbbr: null,
    color: '#6CABDD',
    franchiseId: 'man_city',
    competitionLabel: 'Premier League',
  },
  {
    year: 2019,
    noChampion: false,
    name: 'Manchester City',
    abbr: 'MCI',
    espnAbbr: null,
    color: '#6CABDD',
    franchiseId: 'man_city',
    competitionLabel: 'Premier League',
  },
  {
    year: 2020,
    noChampion: false,
    name: 'Liverpool',
    abbr: 'LIV',
    espnAbbr: null,
    color: '#C8102E',
    franchiseId: 'liverpool',
    competitionLabel: 'Premier League',
  },
  {
    year: 2021,
    noChampion: false,
    name: 'Manchester City',
    abbr: 'MCI',
    espnAbbr: null,
    color: '#6CABDD',
    franchiseId: 'man_city',
    competitionLabel: 'Premier League',
  },
  {
    year: 2022,
    noChampion: false,
    name: 'Manchester City',
    abbr: 'MCI',
    espnAbbr: null,
    color: '#6CABDD',
    franchiseId: 'man_city',
    competitionLabel: 'Premier League',
  },
  {
    year: 2023,
    noChampion: false,
    name: 'Manchester City',
    abbr: 'MCI',
    espnAbbr: null,
    color: '#6CABDD',
    franchiseId: 'man_city',
    competitionLabel: 'Premier League',
  },
  {
    year: 2024,
    noChampion: false,
    name: 'Manchester City',
    abbr: 'MCI',
    espnAbbr: null,
    color: '#6CABDD',
    franchiseId: 'man_city',
    competitionLabel: 'Premier League',
  },
  {
    year: 2025,
    noChampion: false,
    name: 'Liverpool',
    abbr: 'LIV',
    espnAbbr: null,
    color: '#C8102E',
    franchiseId: 'liverpool',
    competitionLabel: 'Premier League',
  },
];
